apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: forgejo
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  name: forgejo
  owner: app_user
  cluster:
    name: homelab-db
