---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: baikal-rdfilippo-credentials
  namespace: baikal
spec:
  encryptedData:
    password: AgAN6vqJ09Y3zglz9TkpxeU4IJ3pdhCpDOmDU8nCSWBikcDOmKM+NhPtz+4MVSgom9LdiG0GWDFnlekUGYjxMBW2R1L1jmbaA7P0LR4KyIQSQi6qmdCyY1eyrmuEckyGMYsqCpczKeiUT/hTlea/azEfV8XuFpcxtteDu5M0LsqsnMx+Bk5zkOLdxHePx0Xih5WFSoF+4X5e2WvirU9fl7xSOpQNAI8nrTrt4ubbzXkqXELbNJv0/tot8rsyTlXHuRJ0WIyZZR2bPoV4ihDP6qHCf3wrDkmDLqLR/VtM14m3rr6qdAWEUFbU51CMgFfICSwvNCT2HTskP56YuHGdE8sB+wRKhA4JllGbgEGhSlHgQtH8wbKW+GQS6n7S7Ez0Y6NmO70XNPtwvnKRpW1Eo+paX4WgkUU+bphpbyoiCEWo70Zr+40tyNLlRnSWlZFtgxFQ2F+sF5AvWA2xEbBA/Euwa9Wv5AQp2URgKujPoZ0NRjk2f2GG6lR1hpauq5PY/BoJOxpoWF6ppFoA9pCg2JN/+1TqDQ6/mZL3e6Nki+uVwMq80cudD2Vpa1p6/QejL9+Nc1v7omBUirlNOwGTgJKd2ft2+xpTZl0DXVvldZLtUSBULpg8ApQ/8iWEYYygVVL2rh8fCfHCEhfeEsXOLHBtI2PITp3b6L9CEkQTl6UnEFpN/pGiJFT/CeVL3jwU0S0CDdD5bTcaG7Q=
    username: AgDAz74JcguEXhNfglnzXUXv4zKISZ8sTiXtpEi48XMw7sy25fScYzan7PdalJVd8lOAFlApckD6r60X7+WzW8r4pGnaChxCprhgDS+MsBFBp8eZ8LUTpVcQ8PVKxf4HV/mDL4saU92z9C/BP6IZihQhcwNKXGzeU/Uzppe1gqqKDuvinhlAYEeN0TcEEwRyfGwdfxuaseMCtUdnCuojy+v03gN66pm+oJqLSl/Qg+e49edBaVIQYB2XbasvXxTpxmL8iHLPxayViL58HiWXV6+ET6VH73Zu7Aduc7SHC2Y4QUt0RPeo0fA8rnnFjg7TcrAmPSEdrGV7bmnNjiXl7eDgVjMTFpZAwopewWwyHBGcce89g7xj+F+B7C9mEsm7f5eoZ8V3MO6CXWZqqicTEgGiCCKJ4kLDfRspuE5MinLUgsb3cCXl86aD/BphbRkxKnO3yLamQob1h+29rIRC6NEpq4knuCY5sKIeme717IvWe5m2at2LjUbzEGLHIXmmNzZe0W7V96qKA/eV1o6yZX1uMX4zMKb24TZlvt1h4G70iWshWNeZJxB5aGU1xKOoXnnnXxFOAn4ZwNjNbXzOOa/HzG9JXvoCuUNzt6mQ6Ao3YjJtPFMBBjtjUsOTMRHjN92ly59ichYxWb3R059LauVL1au82Z+rw2Y/tPTXAsc755fillfJPUxpZyxRoYFeCt8nLgmQWHIPVn0=
  template:
    metadata:
      name: baikal-rdfilippo-credentials
      namespace: baikal
