apiVersion: v1
kind: Service
metadata:
  name: vibravid
  namespace: vibravid
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  selector:
    app: vibravid
  ports:
    - name: http
      port: 8000
      targetPort: 8000

