apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: vaultwarden-user
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  cluster:
    name: homelab-db
  name: vaultwarden
  login: true
  passwordSecret:
    name: vaultwarden-db-credentials
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: vaultwarden
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  name: vaultwarden
  owner: vaultwarden
  cluster:
    name: homelab-db
