---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-db-credentials
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    password: AgCf6h+VBBObO6FO2Jkto2TM41XJb41P8zrqVgGSO6i8g9354xkF3/a571Ae80YBZyNU5SK7UI5OYJupHb+d48RJv4/OPTVKPzeiU2Yx3+dvp3zoc/XzkG4sAuNZ7DHer/LSpL9pPMJgJDa+WzqPaUPl5MEjk/6+qpN5rKX2P67z/pXlo3vgpIGsvHBp4xOlQupttT2bpicajK129iovwrBdlss7Gnty5FmEkihHNfOGZav/iSzRk1xwO8NNWs3rRI2WRIB35JBMwmwfmKVyDNcymgTAS0EtEtdR58Am6VzjeeEZyvW4ZfdO7t7vXznroCTwq2KhbBQhwk7jnPVruCZWwDnuIruNwYbZXnU5Ft3dh/hNrGYiAg/A5D44GPuRvMtKNZCCIcoGgtLebZDc91Kic7ei0jt11thZY+u04/IKWg8gmrB8+K+GfWibHxCxWOZ+7GBcuDBsZDOBeILBNXQgphjFWqGmbaBJv4SxG0xUlKFBnvWLoi1t1R3H6odxaLHIJnMPg54lskn4NsdDybfJ8kzRwZpr0lpbwddxAKLdPV4YczOY6aviNUHEV7tLDK8b6rrJRkBZIZKoTwy0a9ztGSQ8WEq7N2Fl3DN1SQdk9ChZP/1ywvBCCRafDIscqoz90omRD9YDiQgX1oSGozwNY8Dm7mhPzI4Bklp94UEp5bNO2f1793pwTjmrfmmjawNoKtzrgexBo1CA5IPyBQ==
    username: AgA2l72jw8JrZk82sSevpJXwPCL/M+zu1FVye1toIF/u3dcWUBqng5Rhpqej9C8f5ts4ddY6qNdbZEJ5tDluZtkgYBM48PRaFvoy5pG+zmk8Cosf25KGBSRz3ZQitpZUqZiYCXQcNd5cnMmvoHQlNOt0x7U1IqBHHaRFc4p28NTLrcVE0ELTjN/YU8z3/N/w4FM6NTTcDvzc8xjIug+qmEtFdrZcvSANGISaE63rlcHKXNmd/gf423R56gDrPnMVTpEO3na2QQjlKykyItY8kr7Qpik2oYFZQ+HeV2ZIG70wCrVzheu0C+bbhf0wJyNMLTEnsD9Eu6P5PqHe5AS0tKoJzU+QK30ysD1gSOvEzVLt02OVBZQbQNeSGRJ/gIEunt5UGrWPOBUquM05Y9r/m+QS3cmhvgL6XQAaFyS2Mqe2hJ+ERgSNhvyLHWEfCNO87Kb3ofS256FYQLxDXT/kRqRSIoO1EPErA6NwzK5LsbgrUu7Zqm9RsixTIkhuwn20qFTBKpTAjEo2JYZpsXhZTYGZSTki5Y4IgVBYQp2nFJC6aBhsW7Hrem5LuBvh3pyKA2qM675EU58e3Nx9OSi92HiZN2EV0JoTYtxeykQOlq47kx7aEgTrIMf51Xw00wyBOMqD5FVUTcpSvTw5bD5uJSbL+2VEgkwHbXHIBqJkuIoJWqlnn5os7Y0mjb2fdxDuXtOsR7tHg9OycWKoiw==
  template:
    metadata:
      name: vaultwarden-db-credentials
      namespace: database
