---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vaultwarden-db-credentials
  namespace: vaultwarden
spec:
  encryptedData:
    password: AgDaYdYtW0eVaTcTh1o1BDgJKT92xZSGuN9pk+1YcwGfd7QNoWZ/EUwBresZRsgeoMlwu5CR9qfcfhe15qz59NrHe5+HAyQ/LBq3VtWfZgfl7QjV9sX0wnYPvoGripeWeUh0SAGVlUBxxKuCIeBALaw2LXxO8OS1i+sb6znqjL2TKWGCYWqEFVrkZBSylLZ7FAX6GvnV1D1reEYkbhv2YcWOSIOWRbEx/UEGcsQkxMknjZoZOKrU+rs1SXz1WJzhYMhiS6jajwRJxVuDNsHJMZxesAAuvgpCS4Hd6u9ZcYW6D9LGaJBCYVKi8diMqnyRO+cZOp5CIJDpQMFiuAd/TmPhyxEPoeXodhBthYJPd3yBJoUmYPfJPG2pQ485/ruc5WmAEbEIdZjgTcOnSZwGh2p1uxZjEiUNq6iMoaTDhZw5MATW8aW6rzpFsNVV6XGPD1SWeD04ZWmO9IjZYvOwMx+TQjIZgALQnDLX8V9eBeKPWcuLX7GiYOxx87bFm+ywt63J0aqcoUiuGzaiSX1Md+IYebtsYeFi40qoXAjgROegWzPHGnRv6KWIc3wfzvogADfESf3qWaNsVd0xTctXZKd0PlG+1ivzxmBj3EX6lFTStoTeVAL/3flSml5hENfvNixC2xVaA16ip/VmrYMjjEaiGvjltEmMNH/WHFGGQp0X+bJiMxfNEkFdc4yGXzNloXugWCeCMpF9k0535h3Tng==
    username: AgBrawu+IgDpnJm0udqntsyBdwG8u1fHWc59sxcm1FxrXlQSkH3hvR5wxmb7RAS9GYFzPkaHia0CtvhCD/EQrb4xx+466jvjEqFdfd+UIQdDl21ct0m8F9wTG6N9wxoZ5Ipk8imw+tFD9cjyVVRLE722ekz6BVv/EEQdUj5oNyu+hHFmBRo9VXv2sqU/tzHkPLjiTPZphEmNrMklS5Z5ZdkZeLa/ZUKjXrk1ocQd16qgRsYVxY0Ux+M0qYE29yGx6y14Fydm85d78eNhSAtqHeE987BWAS3mMXTW+tLVy3eUniN2CuqMuW6jVhzb/6PpTvWsvB/+F2OvhqXYwvn/Bs0Aohrd2LCzsmuR+799pCJbbGRk0uaEPST6HXtwM6rrZquYZDFmx/clJBwxm1uLN7OhGfc2gwPvXTnXY84eBPRRidCkFTmubQB099Xp/2B7MLVYjhZP0cYbd8ZK/v7EayCZ0zAM1QFLsl8OAQvU9S/xOilG5B8q4jqIaBEdDF37+we69M7RSXlBi3eI/sP+2LWrpLJwovgGGlw9NHkBJaPkbJXPC7jTOulA3WgDCzSQ0RhZVTxahtw/kKegchd/xFkQNI60yZ+f2BZ6vVn3rEBmd8k+F67FnXO8vsREiciIsMLWF3xGpJQGJ/DmMk8b1hOwtTuV//L6eV2P7upDX5XZo/3Lo88a1IcVLRLEtc16F3HeYYxPvEoGS31l3g==
  template:
    metadata:
      name: vaultwarden-db-credentials
      namespace: vaultwarden
