apiVersion: v1
kind: Namespace
metadata:
  name: vaultwarden

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: vaultwarden
  labels:
    app: vaultwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vaultwarden
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
        - name: vaultwarden
          image: vaultwarden/server:1.37.2-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: DOMAIN
              value: "https://vault.internal.fferrando.cc"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-db-credentials
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: vaultwarden-db-credentials
                  key: password
            - name: DATABASE_URL
              value: "postgresql://$(DB_USER):$(DB_PASS)@homelab-db-rw.database.svc.cluster.local:5432/vaultwarden"
            - name: WEBSOCKET_ENABLED
              value: "true"
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /alive
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /alive
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: vaultwarden-data
