apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fbq-config
  namespace: filebrowser
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
