apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser-config
  namespace: filebrowser
data:
  config.yaml: |
    server:
      cacheDir: /home/filebrowser/data/tmp
      sources:
        - path: /media
        - path: /data
    config:
      defaultEnabled: true
    auth:
      adminUsername: admin
