apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser-config
  namespace: filebrowser
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  config.yaml: |
    server:
      cacheDir: /home/filebrowser/data/tmp
      sources:
        - path: /media
        - path: /data
    config:
      defaultEnabled: true
    auth:
      adminUsername: admin
