apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: filebrowser-internal-tls
  namespace: filebrowser
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  secretName: filebrowser-internal-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - files.internal.fferrando.cc
