apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: jellyfin-user
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  cluster:
    name: homelab-db
  name: jellyfin
  login: true
  passwordSecret:
    name: jellyfin-db-credentials
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: jellyfin
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  name: jellyfin
  owner: jellyfin
  cluster:
    name: homelab-db
