---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jellyfin-db-credentials
  namespace: jellyfin
spec:
  encryptedData:
    password: AgBeFSsWklDMLpWrhf/vPK2x1WgrXubvm8sHIP8E9n+HG/J9q5XG3+YMYMnp6tj1w1QS0UoczExHL5GNWl9oPf5R05cbE6gY3zV5xc8HTYeMVwck26MDcicexaVwqNrs0L/VC/G8028KL1IFMuZK1xbwJ+cjd0H9Hgfif78TWV7RO2Kh3SFnEMk519nrRFIckiA6pFVmg9/yJERqcQZj7o+iBqcmVQqvN6YUfRlWZY4slIbjkIvVtQ/LCdGMskQncLooCcmUL7g5rJ6fNekUbWa1xY0G2hn4g1ELhHHDooWwS6w/oVjeOaehxiyHGmFAQ17TtxoSmkHrBJMG1zmvAkCGYY/pu4KBwEMZ2Pw3XWJ76ViQw3aL3SppGUyxmi+GUCD8c94k2Peapwu5/cGBMO6WvuQbSAvzA03WKVTbn6Xjx3/oEgAcxouDEmnY45N5izHl+Tn34RHvqhgWqY5kcTiX/7ARO7R52xX6JRsg3tQVAMjR8BlYCunwRKU6WGsPO2vQwTD53iMicgxWl/r75qGWCSoSIU5QmYIIzYy3ZbcKDqq40tvv5F6G73xmzxMEPzn5ty81QDOzRXXE+VefXeCg700Wc60PsSLfCoUHW38Asm5yQOAM9zCpRVvazvnplHnkJB6x/lmzPc4QZrvCd5omxqJGwXSiN9H8kK9n23zdlvZGf9Kh2HYFJjYQBc4+2JYW0hm7yCFGcUcmsTfV5g==
    username: AgCf0S0f/hfHp+6ZVLwIuFig82Gh4auOcSZM2wRhJaqV7sa2wpyXy4mETBUMqAQx5rG5zabpqFA/Ulaa9v2NaHzr+mskwI780TvnWmFnJmPEfTd41nG7HKlQRlhmaOM+l9dO/TUe+k9H8LXaWejLsn5Z1Y0TA91CO0U+xV4/bsL1zyfSgzMNnVPaSPlNpjpHSj0mKxjWUG34fh3ZbjO5HkKLgiLb11Xpu71pE6MeBcDngZf6qySMjohDTcI5pvLnjEmpCLOOnA/BcvTos/axG+j/9QkpQkEEnU8eWLG5cuQUQmAy1i5uHIXDQaWudrUXNvUM2FL9icG8OhHnx/qKW8egDhpRnGytShSbix1wS/sc/hDpRZ4dYEwoAQntJ+JmrpP1PnDJcMESjq/dBFHNU+kwrnMQq3AJY5shGJ0+qnllDDnOK1cHWB1IWabn+LagiuXr798vWTqKQE7IZMwqugTFl2iHBxrB565m1UnuLslk3jE3N8RoKRrp3b5s2Nroos4uR3MPky4YioROasldPe818w6ddQ2LHDk/KitmGClEJ4+VWx0yg+3p9LovAsqjOHeCRZP3FpeY6UwSSIN7ICZz9fbi4ZVBSLnb8BHjiYqcNLcUuh5uGltOC7YDnsDTFDZt1atSwDBUABd9sCWD0Sp2GnoeKm8E8hEG5KPaj9/ZRuhPDAmsGmQYNCddi4FPiCZWfmCQX+0q3g==
  template:
    metadata:
      name: jellyfin-db-credentials
      namespace: jellyfin
