---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jellyfin-db-credentials
  namespace: database
spec:
  encryptedData:
    password: AgBK3SZTRKdNWD0RHt1ornPm8qh5j2pVnxuwrm4dnQiMiLIIep3ZLhj+CYBoG8Qw64huAMpEyaqfw20QyyVSmUJgDN1qYbkRqs2BYmi5U5gJGgzhcEavqKEnObjrDw9xRrn/KmjvmKc/8JhKBmtGLxPNLNo1PEcLY3Yx5nMtC/7Wk22ctpt0aik+AWtFx06CEDy7KcTyO5nLqHGPDfrLBP/RX3re/jTRwcxSqefNkcjDw2k/sVWl3FwjBURaaqXCOV6J2wSbI0by22/p04+ciDNYDSTjowil1rRBVIMN2Uu4NovshhrR3W2URZCFSfHdShl5FexySDF4hIE87cz0iMUNdF8HaCBfjJJEFB4R2F1tQn1Gcrk8sWY8HgsZfOT2nEWikjXRLpJMxRmALHpyxSw/44sIHXRHEnJwttn153eyFVtzaMDzJMWV0TmyH2fxH40WfOk1Bt9raxX9JfWzuXfOwKoD+Vy+gPDckxUJtGAf/fgWiTxvsIyatZvYnp7Mxj3kheKmXq5jjjfllEtPmqNXKmnzsDz9e7ZiiTfXenqI31BP5/L680M+l1nwhdDbm0g1vjN2yKNyswLQSFNYFvBd2Al8iNauUFIimkCTXc/QAQ8uYDtUsBxNvE8Y0wAOFjVz/9/3hWqBMGcQJ+GyKQtzmJt6fwq/Ie1Atn63TX/6OaEK5QOHJlYilvekBXwt1Z9qrXGlcDMu69YW2GOiCw==
    username: AgBydcl8BmsCpp09k0k2US08gfHUpWO1Y9p5KnZ3gud19kSlHGogv/54F1owphFUKp4qcFaSZ0imFSRi7znP1mcUxZ8TBl/TBxLiN45gmX4iJWfXK308mW4CL6bx/tR2z84lbcd4kIUYgt+AE0qN1h60BeRRSIlzd/nwU948ejBhmBYGgNMRnsgi/VevHR3vqT5GQFhjC5HskpHoCikB14yEuHJEtND6RYj9Siy8WONrbk57kre0zfdn0Loft0UMj8vvbYpJubWaEtY1RGAMDkad439V/1HJ/3gPLhoPxssfT5WBMBWfImlU4nKZiR8x/WHToMEiD49On3OAwj240v0C66nnzk9i+9uhUxV7xNTzgPgxi0QwB6+5wAeiSPjG4Ob3Tig4StQlFROp0BI+ot7YtemT8t3zT4rJHCWAIVs6FVox+62+7xtigi8ssXfE7OQiYfowKiaCmD8bcyXNjY44MuBWpgUwlbPjLohBzcchidj+9oWUujlEkfCpAPiQ7rUQbpwuY4FXzfoqNDYcFkvvRPv0E7NrxURpXw+Zy9Vu2mMT3zawyE+gy9WTpuCRYTDqhDluUSMRtuuTAiV0hmYa6caTe5OxsBxO3fB3evTgZnbQkuNWND1uidSvYTgWDYI0AWbrHi75XKSZMd+zzvmmILIn9rsZs6KI04GWxqcebgo6kdGP95gt8qQ1oDetWrWvq8eZmTbOIQ==
  template:
    metadata:
      name: jellyfin-db-credentials
      namespace: database
