---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jellyfin-db-credentials
  namespace: jellyfin
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    password: AgB+nHhFBYVYeF2w4IRfm88UkJDd5cNlMt8eeJ9ckbMbSY+sh9Hs+D9azL4qrWCMEqn9+kzyVIND9hphSNbVFZZ4mR2qcLUTujRoXN74ZZhsd3OJZZwk/c+XcBsMN6eyPZN4ZtX96XmqLvKBwhQKomfH7L9rnZrbYgG6Q1PQJV8lPz0VvnnMiJpVvuEWNU2GgU92bgE/gKzcyJEoDyLeNZ+CFwc9/ztDCMUWqa1xcrFJtsQARwo5/HD8wgQkYTekYlLpafu728MtgTpUWBmIqPvYhJCG0MQPEIxbYiaVWZavvs2v0LhMpyKi9hz1419tY2AaniMo1c8h2zt9mA9lnCM86ahSO0oei82E3/9jm86k3TjCcZegibmmYaGs5G5ELEGK77oODHIepTB5f/y/VWeQ9YRZkfRBpmeJmzSHrkQcha4zgNxrdUPAqLBm3G6MDaJvjOLOHpKcVZx7tHBrqy6kSoVfMhRQiHazyjweD1gS62ekIHlS7Anpw66Vu5h0j0tae5tf+fpIViBjttL4fKW3dSpwpJrCem2VKFhpZUSjDGXfkw2v/cjNMTvVx7H3zRahIj4kRUzq+SSG/Uo70uydjHGAED+iBzwxt/DIMXFokJ+bUKyCUvE2wGj28v7xrSZVLKZklthlBM4KmG2WahTadsAzkKvXPhUWURIZ4vfWhZsdGudfePhBWUMh6IybKyzW1NyGXKtZ/hGgye7Gow==
    username: AgA5rvzIjvUAlcA/kbfmZe3L1BWNM7DWiA1e78g3Jky500Jyn6+sgGhJo9nN/MYzDGMAPHGjl6+ndj9q3XO6k1iyt9Hrykhb6yziTCNiDroVToav0UkQjnAcC6iwHqoUzMgQpUn7jNvERC1rKJ57RET1k1cDlF1xn730pGMgkeg6YCTrWONtYR2dMiCKIU3LjiJFJrxaDpE/gS1N9ScSbDvGHcUOdtG2h2P/c8QsyQ4jG/U0119iPi/pZCWFKJHKXyRCVBsrU/jrfTr3oNclLTgDQ0Qju8vhv+C2S7wILeORqw1SqfFSVnjUS3ccHHWn7KUypsdr2LQK/1bTu4KXmPWpq/k3wc5tyWosV37JoIE8KJvwVsfqDq15fVEXNMT+9NJkg7WpTsOZTw+d+uS45iJuV8fAKAVbQJmHbWUe6BrOFhAhHrIzXyt3uA9yJnSUn+z96CsM1XwAdOd7+oHAmIUOvaL0NIjBK97pUw+36yumwFEc3lUjmJeU5mGCm0LI87NChuLuIAfSD02oo7PRKHbREks05q3hm+3lRVWT2A4+O/f+uoEWibjsHuEQca1TB9ki5QxVV7jwwGL8x3S0IzrB9VZ3DGp1b4e9rxYsutfEEmHPs66doa5NU9BJ7BqhXUjDsmvMD1ezO7SZUJNWOnqVMgqosJHYMN0MWqEnwAC7k+krCRS5YmJb872U03emBc9Lc9o6zdjM4A==
  template:
    metadata:
      name: jellyfin-db-credentials
      namespace: jellyfin
