apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-internal-tls
  namespace: longhorn-system
spec:
  secretName: longhorn-internal-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - longhorn.internal.fferrando.cc
