apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: longhorn-auth
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  basicAuth:
    secret: longhorn-auth-secret
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-ui
  namespace: longhorn-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`longhorn.internal.fferrando.cc`)
      kind: Rule
      middlewares:
        - name: longhorn-auth
      services:
        - name: longhorn-frontend
          port: 80

  tls:
    secretName: longhorn-internal-tls
