---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: longhorn-auth-secret
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    users: AgCREDJt7YoN20zILMm/LnKtHit1TeqH1IDqGLjoX5CoTcNsgN24TUAjhG5vE7Ka/FDaVmuumsoCG/5CrDs1DOZKwWjDGWn6nDQudsVUZyadU0zYKUz0KDS6aYiUlEgiE2GCmK5lIuIEABcUbNuY5O5fLVUdV7eu8oCELU/uuOyStCGxXY2YdeXNyg5UJ+h85AF4xluxC9egxshat6DvCvx0PjdZZHPPgzAkCkN89lXdmKwaQdrwDELbXhA2udZ5Zb+xcXQTiIrOm+MhuRzSJaBMlpDj7ZwJTEAPqIQquleTLyCVXFKI+RDWgMqx6H9S+c0G4w0pl2Ba0jnBdwi7I6KSVxUu62sY8G+4Au+Bqz1B26WbZ2ZeYmt6M1WyYWP8f8RObURl92UlBu3icJU4fPT6hP3QNDTQEond4Cbol4oLC0/F3iW7gkCkNTxf82u7t5CjkA+C05bjT0T0nnTMTqEO1DKkOv5Uym8a56yYCQobb36I5d+UagyKL2G91a2mUrJPrmaQu2qw3zVWTl29IUmrclIek39Hje00SBignFsqOUFzBOE8LwKe+gCJzD/kBnuNOnJTSxdwY4FTIg3eomciiIee75GJmDkHART1ZezNAwmeYcexDVaDIybelWCMupgPbSGcc6I3vsVvQgS+FjR9mFWkZgsReuc8Fnuj0bEYeI3d7NtYJPikKoDZ9DUnLv0cFIooaUJP4QbXtGWrV+JpW+eNKskXdn8dKv8ok1f+c8UdHWg1dJWsk0RY
  template:
    metadata:
      name: longhorn-auth-secret
      namespace: longhorn-system
