apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: baikal-tls
  namespace: baikal
spec:
  secretName: baikal-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - dav.internal.fferrando.cc
