apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: baikal-user
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  cluster:
    name: homelab-db
  name: baikal
  login: true
  passwordSecret:
    name: baikal-db-credentials
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: baikal
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  name: baikal
  owner: baikal
  cluster:
    name: homelab-db
