---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: baikal-db-credentials
  namespace: database
spec:
  encryptedData:
    password: AgAmWAvf+g5oiIAtbPxTJZ8FTI4OTSXnXN8ga7BW/97/nNIcrjKz66PyjMLUFcJFI3v4mtlg04g6DViPvdPw4q3hIJmXEr2sp/FPgGzthopUoSI7TD10ghEb+6OhA1xz5wHKwYIQTJobado3iCGmFl2h65Gzfeb2KKEMILLmWJJxfb03Fd0x1Zu2cOXTnp7Q36Og7CGP1AaXC5Ard6sDDaXF7FR/379Im4EmU8qguBpukTGhZxI7MzFO34FVbWg6gsmLdbJYP+q2jXrIga05qllru+gmXzKp1+FXmFerRWKttA0Cl67a9pX7CJnvB8QyHXog3Qa+ghJFp7dkhDU7HCaJTFbGiZtGEFWUd6c+iCREwIwdnlQHx/+r4Rn57tNsOcXyYm5BzqXRAvlAwh1oeuLQDvUzEzCnhq2ZWKK+iH7Z42/ApGDrk/5SB6UbJuk+6G7VVH6VHtIjmSx1Fw+vv+UaPyIqXVEkgLpXd2m13Mfyx7viT7EI6QSVV+75IKXRVWnyANQDTCArUriC7AwahrJPrBwTStl9ASxQQMV2uYq3+iWjXqHdywHMSPCxCiwC+oGlo8hISqvxxA0ZJUB32l6nBZx3Lu8fOOD/ppBReQaCLA1BRkMVTzmVPwfx6C2ulkU1G22JgXzNzx1rqoYa91khYEHJMleJhinuc7S1p2vrzFmoaQtIMy7W3tAP4u1Np6u7k8iLwSmF0QvQtikgtw==
    username: AgBLyG93DHhPYgPRfhw+JiVRp39jzwQbWzv+nW4svGZX6C73i1Fc0GdXd4DTyC7FEWgNt4V03UQ9HxJl2nqpGVUy2+J+hblD4OIhjE02BjTzK83Z/YnS8E+oTi2mQ6suiiqau/VS3hql8yi/ZltWNy+tudmeTA5SHTivRhTQumNv+mnMb5HAOeBaCD3cl2k/QfI0875BKE9Eb4/imdGptxKdUcfB4NVVVEbJXisNpSX0arqBHzorzbOnFyLuItyxjMDMSmn1FGdpiP2c2kLILLBTGJEUoyMJOt9pBu4qufhO1+Rxq0mgI9RK1vXgI5l6F4PbXPFE1wMcsdv5QK4tQqDkSmx7eqFhpuSKvn13YP+EGFgqJczPjGSJlIhAdYdGf5Wlqu3nk9UGDza0Uogfo6YMaDovKpgE888VsGZTPGK0zOCI2SBpbL5Uc6qe5iF9rSnkfkyNKRIPSMy9FWqfaBu2y4VWFtP38FwpOIFkyONTDUlQx7zIHGN/kQuFkZ/8IqR5+sPp4JNy7CAXYAPcFXd6ORxWa1PfFQweLj82846vXhieGJo5nnNmLrcsw1GIu8/PsiNmjGN3zGopM5mxXw7a6LNIHrIJ7liSXPzqjKnF42VoMUwgOljtFkFvVkZjOUv/ozp6ZEiLUpkcC5Mi7xhMK+yCQVCt4jsEK+cxH3INeM0WytNwZ+8Dq9zBdG9lHfBFh2+Hyvw=
  template:
    metadata:
      name: baikal-db-credentials
      namespace: database
