---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jellyfin-db-credentials
  namespace: baikal
spec:
  encryptedData:
    password: AgAnB/zv1MpjMjzw0An39ItYlNbKbSkBlnxF2jizOJ99hC/MV7+RjxAjT16Lvlp+3gwOZAyyKe5aMWXk7So16PdRPszHneuaGSvq6sh9wu46QMmqiFCmVGhiyOxn35NuP+8VXM49MrJPIXzkbIGtgv03l6ql/f15PvfzZdRCzRMxdNFtUUqp+WV9RW1VyjWGzDHaew8xjv0kDKs12jCsROt4qJPRdvPTqCL17e3AZaDrToFJ6GBWseVCJ8a4WMf6zwWMWZdN8I4LGOA78nakTSVerGDUCFmm0yZxcu4UqNeXDx3yQWhGrs0L+j7XoJIgjp43afEF2IttCfMtlLHtLIbSpEJZ634Y9g9FHK89v1/AlddXjlDGsdttGjuD7fr386pANrDThC0he1Hsx2l9NKNXbd7pY9KHcS+ntixZZvxMez4FsNujGP0CviDpyvQ39zxeAdaSOELo464cGeCKkUipMN/lXan2MJ4OetGOkHJzhD/z2SJDRnXL3TVVy9wlKy+aJUYsdohwJ+fmSOPOORrKF1TZQh2z89dynZmBxznLMK1E+4iPeuyYR3wLteq1tzG87fwFwsROFB71NCz7worL1asLiTe/I5Hn2uHx6eso/iJ/Bx2mXvmuVnlDTJDa8tg26miR8PK75/z5K7FkX23RUtcugf8dSe2D4scbK0oyEDlSU0omfGAqXJoBCLKY7NPpT/TL1wR/jUWhbOblbw==
    username: AgCjyqgY+GprwT3sHNfIkWyf/Njo7S2suH6spPgp7OjGnU7nw3talX89yJT7bt/UQNj45eqhSHRdnrhFIlsJ8JcUXumdoAJVAkAbGnQVrgv1LEWlQ4iNThWcg2lN/6VDrY5nf34D3ja+2LD3WinRw+HcVUhDimZZZvNosDSuhlt0pqP0LbHe1/kp5nrFqT3sK5Y5Dfj9A0W+Jrz/XjOpQSx0Y/V2psNe5yYyZgIlBi780vs5Ijv3gBSUnEm7sJJtWgXGfp3czOqRXssd0d6Ri3IfOmiqIdMhsPAt1zw303V94ffI8Q3Y9XpnrP4Mx0v0MpRuEGhubfLG5IJIwhytmj7NwWNXJ0DfsPhcJFbHcXDtHmmNq6Dhzny7j4XTbYLYXkLngPCEhbfKfL5lvMT0tf8Khq38FZszcZdYvSClcQWOkBEMATWxBXhL77PU2cOfNrYq1SosJJz1Of6NB5snAF8nwVMbxTiuxT8bF6Ii3TUxLLI6JoX68QnWIcAROvj7Od95osRi+qmILsrX2GnMlis0kWHxM6btLkASQU35m7Y7WrgSabqgJjhoSUVxDrdSjM5A/V+MQS7oF+/zUVyXt/WzAbNckoZlo86YxMdHEsRhPUNfLLUbzMz7H2QpQMAs4D26rZoiS1Wpv3CFhx87F9DcuMaOCccsXSKyo9LVnWklNDYJ1Cj69dYOYshTQpFptsEb3g9Lzhs=
  template:
    metadata:
      name: jellyfin-db-credentials
      namespace: baikal
