apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: seafile-certificate
  namespace: seafile
spec:
  secretName: seafile-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - files.internal.fferrando.cc
