apiVersion: v1
kind: PersistentVolume
metadata:
  name: seafile-nfs-pv
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: seafile-nfs
  mountOptions:
    - vers=4
    - proto=tcp
  nfs:
    server: 192.168.10.101
    path: /mnt/vault/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seafile-nfs-pvc
  namespace: seafile
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: seafile-nfs
  resources:
    requests:
      storage: 2Ti
