---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: seafile-credentials
  namespace: seafile
spec:
  encryptedData:
    admin-password: AgDGsXNxvaqN8iZ/2ItbeRpqe+GyCDF7FQxrZQN2QLV1YC3wAH/DzcIjA1p5SbjZRRczRYov1H9yL61ZDuAdzI9wsdj43QIl0Oc5D567q1WwahyRXj9SLBYPCGMH/wku8GDJLHt/XUiWy6XyyMcmIegvLujszjfdvnM4l3lUA7J/NmI3SyxJdItCskVKqT5knojakbFqwKbQh9x38vsDlfpsjvf7zT/8Bhnskl0co9D2h9ulHq1risb4U3sNBt3dl3jRmLfCwr7krhA70syCypag3d1ciNbYiQOmEwLSFUvSTCPNYme7k+tYxQGMLM78gqDY3KTapPR1kOtY+ys/Hm9Z0eBS/KKLQSHgu9xOQDPviDi6WHfZWz/u01zNkPHr6yBx4Wns0yRvU4Oob9Ua04/9Pt2FHFf3S6f+8w4YjHCbispN+krirNRyhG39jFzxyq9jSwgxvJItraWf80vR9wO7lI0Fw4U89qn7Ajw/gUDJaO8aRJzjpwAXc4X60DDMUPZqNXWzPO+XYjCg33cwv3CHxR9VcKv5hF6axsuFq7hZI1I6E16hTKf+vivkIG4rKJJRezwZ+d7Ihr00etzNIwcIfSbCPfYPeHVhKStNGipAeYtdoNZ4V9+863LXwMAAb9sXgU9oQhLPrG/3c81CD58GiLjSjOp1uX41aO2CbnfXU2EY0e7N46/bL2tZ31X1JBMwTmwJ7Qm/1rA=
  template:
    metadata:
      name: seafile-credentials
      namespace: seafile
