apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lastgasp
  namespace: argocd
  annotations:
    # After the CNPG role/database (waves 3-4)
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  sources:
    - chart: lastgasp
      repoURL: git.fferrando.cc/rdfilippo
      targetRevision: 0.1.4
      helm:
        valueFiles:
          - $values/infrastructure/lastgasp/values.yaml
    - repoURL: "https://github.com/filippo-ferrando/k3s-homelab.git"
      targetRevision: HEAD
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: lastgasp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
