---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lastgasp-auth
  namespace: lastgasp
spec:
  encryptedData:
    auth: AgBqH3KBLum4jFD4+9qKQw1PDzAcy1d5vdJjkBF7lgyxYFPU1LA/LInjYHkq0EPeCBZZpqmu7LH0tbddU0kWrTGX56HVsMWTJPtYu7uxgwOxNzNNkpAFChdRq4mdeYINCy662Tl4h49JCBEDMdBeXfTNPt8x6Xa9pg14zDrS9JGiZ/MW1QL8qMz0elLnZYEGRtPpAymKGfaFmIOuCJ2XQ59ot/mPta884C2XQdzGoZBLGvUHsvWwIv0i18huY6zd58RFelwOHmpCsgrEjk6SM1iyXL9oo+ZAKaetpdKCOT4g6+j57/nh1HOc0y0GJOKxNHjn2P6apMBsaBQOkV0RFJApOnTBU9Z2W9JavfWNUOWbVfEWg02j2r6xVti6AC617TO5UYwC/SFQuXrEsc/tCUz/eNbCnJXkggZMIvFB5tjLNsqC/+J1HphEhSSs13Kek8vVH0n2Tos3KLz2g89+DKvniKZonNve2afXhO7QKAlc+9zolgOUQsRx64Fy0tGp7EzBXWSTow0337z5Daunj6//v65i+MHoKI2nckv8k91C1I/DVG2keZUmDRqGMDYB+ttq8YW5qTh9MeXG5OFbxiE/Tzw6iesHyLZSevrv54H0OEzXnM9kb0oERzCWQZhqTIJp9YuRADmi9sLJwPDuvXhIphOr9uEC2T4JAI++E7aRdpn/Us5Wbtfmk1qzW0ytMRASIDtwPdqD1khHKbK9CirLV62qiSZOmCooMh1Qgf6+H7ARWS2bEHn0dUlUsl8V/0WMPZVYPkccWsh4jK+PYoxOj1Tgf7w0wQ==
  template:
    metadata:
      name: lastgasp-auth
      namespace: lastgasp
