---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lastgasp-db-credentials
  namespace: database
spec:
  encryptedData:
    password: AgCYeKjm/mlM6YetlRoMHk8FRojZZmKLNpgDVajFPyeRhuGMGDXnmdf0O42J+uGk4HDYG7VePxOE6+F86XC80p1IkTxb6l5vOOGVEjEVKEm72Lg0WvVKYWklroGOfofpamk07BlqkLOQ+XYXKWkNAjGvxrrbkNrTb35puLIau2Pb/LPIn6tGM+XwcmgJCRVehJaCEUkFp5JjcN3ThqaxM5z/RJUT4eCWqqSaETIM9FxrkpBKYt8/uxZbyhf9iBGFolmqBIue3uv4T/U2LAR4xN7KB3rKIow1shNR4jqXPL84IeuKH23t0vlDjVsi6chmowpB+QULHFixSFMp6UoJ2daS1RDroA6l7Pg3f5kcwWVVMMnSrGQ8X+QT3IEX3Vl1Sv6gVbKNlBFQ+DNrHFLVEUW4oUQsyzyyPY+KCMj97JP3Hv1lkYuUFS8r8xw24bQa7+t1L7zrW8IhvN1QErlTBWSUzqbCikmL5UFTW16PXC5ldfGEB0s7/9DPoRRtZ8xXij47FjJUL0IH1ZXPiJ9XZU7HNIfLoEvMcN+3SOAnJ9k7D2aRAVL9zSuhYCIMj8QN62Gf7/0q1BPVFi/t8/bHFTGa45hUbteKDisvFAtH7HtF0Dlcvhz4pMC46DePT0Lyg86+Lg8U8Ea9Ekf8fDS7eHUflrio+wwLf4wbt3bGqxDLxzEyyImF5ilCnjJW5dBMsgOOmybz9CPRnEWNUj5X8A==
    username: AgA3YhLlhtz7IcoCQBzzXFtuYH0dzbXBNryoQid4GZjqweA+++7gXA6TaRaxdA+ovSUOqUAG0i/CSm/PbDkzoh+Z5ShqjOBj/tW1hnDOp/rf2/ICaRyZMcqJd52f1rj2r+6hLfr0kbHEidqL1kS34grI+39hK7OjD2BvQDR1bCTSOGo0Z4WbiQ/t/pHabs/onXuQV04xVh/2pSXgqV5OLqeaEbaA64A81yrUMCPHiiZTphL7mw3vAhSeHz+lrcOW6kegiMfDYCy3sda7M5XE5POj2p+3ZuJ7jG/J7Zl7cpc1UqX8d1Ck4AQLvuRxtV9Ux0SswU6AoC23/HcLPAxSbbwHojkHt2HU77ksdCZZ/nwyU4KWHmDcuh7cwl/HPOcfQWMeaGC4pzQVusHHv7u/mAz5lETSlylN7VlZbz+PK1C0f4XUNKrfZjxPiEAIsuvPhl2f1dFxNtq4h2D5+/AECmpVJEkFJ/+Gx1OJeG+fgVQ2qqRnGsui48jSa8FRWxtwKwFROf8MfSNjSzaQKMHegt6Ee3VgC3c1TsDFoBO3Bjhvbft9meniViyT0xw62ovMKjq2pVzrTHEKwtP/y2GpwXUhhr02KbX1gnteEmRL4WjAwhx1ZyVrcAlIYE4PnRFkVby7+wbAvt7GZUGQBd2STDxc6IpVGiyY6lH4+Ycud2NemJgQZaRmTFIVKbnHxBvc4ukMmvfK2u3HbQ==
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: lastgasp-db-credentials
      namespace: database
