---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lastgasp-db-credentials
  namespace: lastgasp
spec:
  encryptedData:
    password: AgBgXPgI7RBuvcVnonpqx3p4TaFAqW3kLUVOcO/FTt+wiSZXxysXCwZnrzB0N3916kA7R8uQQJYxMQt+9aabjysffyeuu9rIy48I55H4W9MIltik9GTbFjkiCVUUNQ9Y5wgA72qdxfadoT+K/u3uJ4+0DFPmVfbQTTidF0G3nbt+ttfo57oegNXdcshUFkSQuCWxLFX4giyNB5jgsP+H9AtNZEDmwZNh7DiLcAEob2mKLGv56EkkJoyll71TiUEpXyp/wZrekqmJ0RReQ4c+MQDeBflEghVbrYE3nE1zQHcfGC6r8zph3MuyAW7wfo40n9uOFcLKfw3MXy7r4eClvjQZVmTX2r+znjiled9omk3SF6YlJj6Y9APmdGPXjHBw9CkzaLxjKUQhvQg9cLDbghSBjQoofjt7uI3/M+2jMtHIaipv+b74eUwNJ0R9tGEIKd0HAo2oVgivKB7TdHEoNoZc87Lmtjg0A8mqas1EGiDRrhm/R4sElKsGRuE8Kq+uVT91GVeI/szFOQwfO0l7GX9Lrx93/9XtBcfKG+KbVaiEhqY1zMIKgCgO9kAkUFlkcfVbz+Jsx9t473vyxXGWQCLE7S14xLCgiDc3ep1UYcio19ZQWWDyYufBfjiq5MdEv7Ef4vKXOXMIr7b5t2DUjXKXBaZEr84p1zcltU7StddSeZOe10/sG4bzKM7xyIXV8lM4Shv8tAC2dUlqc6qLRw==
    username: AgAfrlOjcdjZ2epfBhCZrnwMiwOYWf6Ub5C8G0UKzYVzKIax+D7k9vFYp8eC+ciXyf2rGIaXwGjoNUHr/edRTH8QmHXe5w2Nq1xDLgEgdD0HoLd4PnRB0XoMOGcv4NxWRnOoYTMaxum6HrH9Xl1ZjR1RKeBkwHEQu65pNFnLQze1Zqw0S91gwIenNcV/+ISxv43I8trJMYNZ0tOlkrReKcgj24DwyBfsTGxPw2+WKjEFcJ7QzqQX/uDu36Y+vT01aefzEUm3ZUWENRn5eC3pGg5qkQ84Un+vR4s1OWu8zgzkr3PuUpFf2Ztlcx5Tjd4fVH/0Cgkplj0DDjuUKzbDhjS1Z83vkRXBil+P6vef5tDXta7Fs97OTQRXmnir0TY8bYXDl7+qg37eiDYdv0Yj9ssszPag8aGiFhj4KF1JHMrBjW/HdZdjoOPVFXHjV3qu6diR75cJBU8X5V+ih9BtGH9OxCN/RHHDobheBRmg75p+9dNG3VeKhLLQgqtuR+0mSpGTSnO/XxyvrnAgKEalmlaNtQI8hEsM/Znxhce7YrY9joOmhVgCu2RAtlIoWX2v/oarXi/4UgOZz9CikGkw5vzNLmKQGVVMQ0f8unDdcUOvpFzbCF58+YMbvO0rDOvsSzEYVj516AxJCH1ssog2YLr3g3OP88tJJZlaXVrVD0S9dpLzW4kZBQDVhduxYq4cQEg+GDytYioW5A==
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: lastgasp-db-credentials
      namespace: lastgasp
