---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lastgasp-join
  namespace: lastgasp
spec:
  encryptedData:
    token: AgB8j+TipzMrJHaLT2v4KJFhrBGFH2WQ3+F0C9xeVQXbdyCgj5fWALI99e9EcDU9N8Tfd5smiO1C2JgpdBf9Dok7ys5pnh+35XgmntjEbMU1tML3rV3fnTbBAbq0gthSqGZgYviyP+zNvn9voA7DKjjWJ8dqu1xs0x5zteE12kA1UWKFX6/5kDZNA1cQQ8bigo6J124TvqINe8FmN26Up/mFeVMhGN5sifKRaV++Dq2m60PVg8egJY7ldIeC6VBpiGeGkND5iGvARjfjxb9NMJL7h85F92xtWTqgux0wGvdaUlW49mFOQJzD6Q56eJekR6P0tqfEh/LJa15NnojYIx4GvTgp2iPAK1fJsPtsKIhFEcApemLsN3OM/bsHXoKBtYHQ+TayZI5IV9F9zx4um4j4FLjrQLB4vzsCn8JrAEXG0E0Nqu1DXOYZffKoAG7dHpkFUTjl65k9HCa24UMKqwSvT4lmB3xP717oQGUlMukqpKlj9O5Eb8UU7p4vDNyyVsJhtsMZKnCEop5oAOp0DZubtsh5P0pGmobjwCgkH2Ha453x0hxYZITQw9QNik+//Vmh0KSFngLrO4CH9vS7cIN0eD/zD9RUdQqrk6MCmb5ZK8dUn1crTnnUS6cZ2rlg25rsNd5WO6h67mr9PLqGAdOn2GFJP2F4rMh5qEjMvK6njzBMIjolUk3DFpF2KAHC9Hd1jLntQ9L9DT69OZIMmN/z7SIkGHi3lq7Rn7C26PrY9AKTHlI=
  template:
    metadata:
      name: lastgasp-join
      namespace: lastgasp
