---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lastgasp-key
  namespace: lastgasp
spec:
  encryptedData:
    keys: AgAgMVqRR0XZNg3jl6ArPpQf5JbSAB4lFg0de/bPTj7OIO5NQY1HEUM44vyDl6re5lSdGdGWxfwVTEHyF6ikbJEngM6jHYguEZyfpl0n1boFlbgXVyi/tvOBOrffVDv6pgJ1TbXrROORznQwb1RQhjwr6BIrshtdeXjv3HEgKJrIkRVCwZ40BhO4dPrTijhuTVkFfOxZkRAu8JlpASLj9+jkN1LhMzDcMGoV0fCOKk2SykSoNy+68MPCSO0TQbwJ1TfKWXpapofajIrdAuDy/1eKjRi8FizCF6GCpx4OvP84507f9hnoe8IRJp6nQYG5+x5PZ+ZLPZxkr5khHwC/koPWwpnXAbCeAU63MXEp/ewx9Dm+ES6WEbf7xYtP2TwnAWQL7U/ut+S95OrBpbEjVgNY4QewWk/Uf+VsKebPywkGlIFDD2mvYBVbZmqEdNzwLufw4WakMPblMXuArT1YcseOrW6Sy6NT/okkCDLRsjOBs68kYykuAtLydTiH2kdZR1GPE/pldWdNJyTNvWVZt+pv8o0EzV1abrHqFiWdyeimAVOHGysJ8YbEfUb/c0hi9oWID9NUTNhmKNxh/IT0DFyNIeoxeFepj/yYM1ctbJcuZwwV7HuAy8ZjKKL/LJ47UKzmsG8oeEiOJTA/tymctF8AA47BVwXYNCg8dtwy82jTZmtus9mJYyA8vH5cRks876R/qmS6pfldt/Xlfv2CzzqMO1xoR2KA1LcQGbBH+I9FTnpQ7aUf5z3XQuEvlVThhfm8U6bTwN4T17uhmr3MSMGn8e8UAG5WU3oSJCS4lo+9EcOhVWNJESrU
  template:
    metadata:
      name: lastgasp-key
      namespace: lastgasp
