---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kubecraft-db-credentials
  namespace: database
spec:
  encryptedData:
    password: AgAmI+COF1GYlXcf2r4kk3JlfjisKOVYOfulPvN2NfxmM0vZ1dN+hfu9NgOm8K6f3+xA0DWimYdqijKUtazcaPocV/BS24yuKE3jtRaceD1531WbKiVeGdqHerHdPOKDVSTs4GASudjPEgUOVsuB4T3Igqr1AWCRtzeZWri7roaQZdUesOMxrgrwE8BJVcgBZjiz2V/JcwzzBfw16iJPjK0sPYfsiWG+S9BgfrsUSjPjLGYbGfg5//4+pAJWf4cofmnJp6UHaXIC1IJw8vbt970SubSv0EhiCqfihs6Hd3H+yXBEofub6/BTbvkpKcM4ZeyWUzTC5i3rj5AVUZUklweUDmmZ21JU7jaYlTBvtMa5XewXFO1r6fwrqJ5C2SdSf9c6GF0oLoo7ZIKv8FaOF9CWx+DFXRgXpi7pWgi8mZ9PIwqNlMX2ssoOZ7uyER39s7dR134QrazLdQN4DOMOJ6rY+oAEKU0rmjwK6RV/7Mp4/UG/ME2mHmKL4E22oW1yjVsOUTymBb7Y+1AwKPc4+UxrkaiYNS+jqYmKaU6kUr+xWO9vhrpvA45dVBCmKvq8ctXKSNE3DvAPjjwxtqcqIxkj4T8jLHVrH8bGPgyj108oZdAXvg4d8xoZxB2u7Ql5noA/8ppBBaph9Y6X23YUaLgTMJrCN2q/na49/uN06DIsMpnCJzB5yNY4Uob7kMKu0eHT9SmL09NfwadraC5qSg==
    username: AgBr+FBvInNkYcDbFjIjNIKI7Vb9+KvH4o5LA5oOrLWqYbZ6Evbob8/zfREn+CFef4JeiierGU4Irlkm4Tx2yVZLeFSqwN9rxvcOW/MUYp5Q+M6lJqDKGLfjImWF/YRKJtAg64Bd4q4Ju4NyRKeqsStLtC3z8xtuxLSwVIWo7i7WKzZv78sCUV0FFY0UpZmE222HiCCaHJiYuhCgpu9OlDdLPnD0ocfotSemf9mJlABRDHrCDfu5798iG5xYrDtRP2iGgcjLscS3/6wouK6EHCHPzRtrj5Pqi3GwnxPHFrsjPZj2KibDcP0Z729zjmkFIzlfI80pfX2mvGC0/13bV4E95j3eg8ZZYgOQuLfKMZTh27+JAc027n3qRYODUXGaQAoFKE2dXQmATobGr8ajRZ9U36Yp3k4BfWQthEqf1lbOcHYFCENaBDlLV923rw/mvNZzCffgR6Bn27ajQvxtNFlK06R5BeadM+vnUHCYPQBBUKX1VOk9g5e4cT/jot4XXr16kbZkfnEOuVWSbo7hHBlu9AvCRs314MHqGyye7Py2X9MfgBn20lGzx7fd26xHFAfSloSL/WxoQkQvLyn1h6YddQAzE/9D4MRux5fQSPpv68a9comaD83xH3eJHsbOkP6iMW/TpuMWOgKClrNouSpWnZPnkOpgs/Tpz+6JV9pD/ACxw6K01H6K5vZ3qdMh6PPa7mMX4Q1WCUI=
  template:
    metadata:
      labels:
        cnpg.io/reload: "true"
      name: kubecraft-db-credentials
      namespace: database
