---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kubecraft-db-credentials
  namespace: minecraft
spec:
  encryptedData:
    password: AgBvnYCztb5gIvQVdug3dw79PYILaeztL7POKYOyzBavNujpksrg5lPrBAX76ONAtHrt/G7+PFnuTYiK+bc0gYH+BYMLbdeaCcT2Z5uSxRwddZ6ywh06ja4R/xISqzyc55c8NJicCcGO3L0EPdnzVejd6efjhrKcaTtMlhn5DcOzDCH3vkBaIgJTULLhAwLOkNj32ZtVtYtQLl9oYz9CkTGXMqwKixAKpvLVNk3n98OfI+SjroofWdUkYgVIcf33RExSY9ECTlACFmRub8JBYyc7JNCoDAp5RoNfl30Dapt5cr7iR50dSnyVJUhF0KU4w56OJX9EHDuIn+8xAt7Uarsbq04VnY3mlCy+ZiBH2CwSq/v3sxDQIgQu1XFtub/SNq0Squ8IdoLzH9VwnZjffDc+WGuMbsBK10AXeIAG1YzLRlGddjUsWMemOI/T+bxVg5U0E/m8Si0wW2x8ZXs00RVYYJW8excASbn8WQhi4ms6tEHJFDBeLY7Rs8o/RYX+qdx10Gj6ZYUOtBORuKMLxa/3kjKANi+xkx3XbWWXgF076K1HW1pkLPEEkP0mMxfIQ97Xz6AKozSWi1y/T71S0xOCESP7zCVtVvzI9Vpo432xxRJSNh+43kPxQ8jwbLcLb67esAz2UOHQzNQ3MVWBwThf3BZXEaaB0Wh5SOGiHp38WC52+Pcjq0CkmKlO0pjL9IemiwNCMeKAO2g65SGS9w==
    username: AgBWuJVLfGNnTWSLwu7u7KQDPI5+57aFuekG3nD4Rlf7UTPMQa/ZR3cXK78o2YR6luNYjAyp7MzsM1+MxHXrb4kKGAW9WeV6l2mONgJewH9LAnS7/2lHveXZVp4oVcWiK/CRa1Gn8YDJ4iXOkb8Kf6W1FK/iWNGsZc3BnI0ev1FVbw72gbjxXevYAfF4GaHU7Opt8vhMujzLjruh6dq0YipbEgvEI1Oem/XSJ7As5oXASMNcIusqp+kfQ8EFh6y5NcVQyfz5rW84WW4dGETt6yGKhSlCG4g4M7sImpch5AABWnhqqbEFiq7G7NhyCQek+kpoX2k1h2OoB/G2zRaqNNueDt+bTfS4lBnotywcKtypnPso5kLArRaecem9egPCyctgD50ykCSRHkD/L1pyOuhfL/OhE/xMZJCDY/zL11/8dPjvJ5+knhWKOebeHRWbMi6bCcJ9ZOWLrX7H0K6k9213IZOIyv9jULSNFSBO0LpNLovpwSDW9pprkMqxrUW8c+fX9VOLxfFP8PcCB5YnueRmcxj/xLU5BBPSV52BLEUK7OBd7usKOnWAdiTrRn8OfyY+WV3iXDIsvspgsVMocNihbH1CIab4v7ObeggBiTXzO6W8FXV4qLGBDSaCagWBHbKGkaPstSTwzHqVXcj/TC2DJQ+KoxCT+XsDDD1a0sZsgrM9P/WhsIRaB8qHNXf/ubYdJmkFh7KSPTw=
  template:
    metadata:
      name: kubecraft-db-credentials
      namespace: minecraft
