---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kubecraft-playit
  namespace: minecraft
spec:
  encryptedData:
    SECRET_KEY: AgBw1N8fKIwAR8K9+qFlH4v9yasqsvKlPs4fydO5p19RUp6JH8XSNURo/e7r+lA/fOBabkgnrfXINSUJH5CfaTamYQpmDQvzDUS2hl7cPIJvE1PGkOzZkYLHvGDR+HgBmVoTPvq7YI8Fr0Gttc0M+Ftz72EwH6py8TPzb4+nNqwJG486LQGdruQ0P8NP1A4Qc8yP2JFYN9+KkIrVKdNdeOvjkeRufjbxxGmS8dmam1Qv34CtF+b9ctM9j2aF7FmC10ZxjZzWEfvV9tl1gcXYO7EfX/L7+vkLtdo4+35PeEwxssj3dTijpqNSh9fHUJ0mZBnUAIYBoA1vpZ22kyzwjZ9+5OmeUAOPfVEc7wVguo6pV/7qk8TgTiwC99grBVkc+mh0y51B/GeWNcbqP3p5wxAgmqSHnSUXlSFYGb5IBhuMhmKQl+9WiBxoEoNdnkcOS+MdvPgkloa9k5AegO0W4E0qA09O+wSKBfVaJr3ODutp5W7pv5zv8hxYXQbLALHL7Bw6a6zow81dlIAJZfuACDv3K6xXSyj4WqM9rxRzc4U1WvPNj9h5npgsfiZ5FyuadbXCKaol+mkxBcDd7Lrxf584goCky70X1uwhr32ZFDAfyxydMwyABXX5j9ATffGRlrkLntVsSDCyCQMOkvFTBi+I7bk8JHRjBCvbukD3ZRrlUA9RjivIJ2/INjywYlUYzfNqkXfIes8W9KZpflV1El0PO2UHknWqeL+B05FQ284rvwYkWXkYnRZ/5BcTDzLG6GNmD3idF2LOzZQdkYyQmgXu
  template:
    metadata:
      name: kubecraft-playit
      namespace: minecraft
