---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kubecraft-playit
  namespace: minecraft
spec:
  encryptedData:
    SECRET_KEY: AgCPHUklF3nWIOLxJ8ZZvjTJ26NxyHZW/5hbnYwGfiU5/LspS9mjWPHWQL8tE6ZnIPDpXwValGWbTtfTR9O6CcqOoI/VIn7ofuPnZ1RB1cZkByyDxoZJUP9zk9y7pfed0oDgpP6Jt4KqZt1xiJbfjMXGPlWfLKe0jSTxsRD1V1BjVXRe88M9kUx5syXZ365D8R6XIuJKbEt7RZoheLPP0N+/YEsV740S9hy+4fl0rFIf4eMzDp61vYwLW2felPNEZ/JcFl2YyImdv4RhLacMaFUrTpTSsmTyf25dT9AqIEU3d9scP7hbqf1fJQilmplgtFCqshdxMxFPqi3dYLQPVNpB4mDqsqvA4Js15LZV8Yiaj2YejA6DWz87TAIFntTj/JeMMJ8TKKudjjQojUOWZkOkj2ANHkrb3CkZi5j4zgfwwmrL4dQEq/4gZhh99hy9Arouq8yCDubpxuJbO8eNo3h+0Eru5iNG9iE9/Yugh3Z9DULENPDs4r9IHoJAQz8pUwSDC4uaazFz8b07H/mQe39q9MjqMEe3a3+odDuHhSlbEme1ERzHLVM6M+HyR6ZGsBtmfI2s4olLL78lTeLd7xpLdo/PEKiigul4yNMnWGWv7y+sAs8LEQ2mNnCZst6DlwzK1zkSvMHnR+wkH4TkhGQg/QFHC5MEm+YbUz8koSvnkpzoM5fk5km/RpC0o36qTbse0x7lVi4KRCwZ9SyVblTyAxhHw7lvxRLeeVG8KmSIe+7g3qytjQhrh6Qxr5GheXrceP+IDYrD26JVDiEnJQVb
  template:
    metadata:
      name: kubecraft-playit
      namespace: minecraft
    type: Opaque
