deployment:
  kind: DaemonSet

ports:
  web:
    port: 8000
    expose: true
    exposedPort: 80
    redirectTo:
      port: websecure
  websecure:
    port: 8443
    expose: true
    exposedPort: 443
    http3:
      enabled: true
  ssh:
    port: 2222
    expose: true
    exposedPort: 2222
  cf-public:
    port: 9443
    expose: true
    exposedPort: 9443

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.internal.fferrando.cc`)
    entryPoints: ["websecure"]

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
