deployment:
  kind: DaemonSet

api:
  dashboard: true

additionalArguments:
  - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
  - "--entrypoints.web.http.redirections.entrypoint.scheme=https"

ports:
  web:
    port: 8000
    expose:
      default: true
    exposedPort: 80

  websecure:
    port: 8443
    expose:
      default: true
    exposedPort: 443
    http3:
      enabled: true

  ssh:
    port: 2222
    expose:
      default: true
    exposedPort: 2222

  cf-public:
    port: 9443
    expose:
      default: true
    exposedPort: 9443

  metrics:
    port: 9100
    expose:
      default: false
    exposedPort: 9100

ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`traefik.internal.fferrando.cc`)
    entryPoints:
      - websecure
    tls:
      secretName: traefik-internal-tls

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true

metrics:
  prometheus:
    entryPoint: metrics

    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true

    service:
      enabled: true

    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack
