---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lychee-app-key
  namespace: lychee
spec:
  encryptedData:
    app-key: AgBffovHkSEd0zzDv14Dk7qEpIBHjGYtHM0vlNiLznywOlj1OfuoQvmMgeflKFy3BKSA8Hvykwpu8Oue1Y6L1djXqY9BJt62AWWeYgNPiJFsp46o/NOlVk1iRFLUfNxWHVu8eyLo+P0lQbEcMTx0xLfPHDc7QS4DPfMv24cXgNd+oR1BLG78l19/r6Ck2Zrg0tp567VmOBAbkCWQdyePCrt/HFKu7m0P3TJLOp0xexexXbXUTo2e241JEjELgn5b0Ke4ZW6181OOG9hjXZBZESf79qJuFBqas7ZWlrktAHjS9Ier4EphdRWmKKkFytuxqbKiru3mrBEvGWp+1x5MSwUB2zoRfk/pnUbiA05hBRMFjabhLyb0pgvovujLz5y1Vcgt/8296eh3CKPnJ9fIuRHW/jqXiuHSAsOawflkoiWNlif7O1i4/BiavipjZxtGPtj//s0Pb48KDvnUs56vjSl0LUuOcAeKgkoCHbO1W6XAEIsfTUYXXm19T7y1Rfui9J8jH/gNFTEoPpWI4SvPMiN4sDnRs4b3kg8182V+l08nYbwDC7s+kw3wIcEMdDICqkmztGPzYnGIwlWQTbCSJVQ1BTM+SCcdR02opGi9/E/mxkAyJmnLGyiS1D0A36W2uOEhcwg8eNQnX3NGZ92u33Rb5upEeBHJKquWryZhdj7CEBZKW4MGxXanXzes8vzxuDrJmwJrDjiDqstSWljbvp51xahmDw/HnYs1CYyYwvGEudE37rOuD+LcGVPIiH0Xg1vV9/o=
  template:
    metadata:
      name: lychee-app-key
      namespace: lychee
