apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: lychee-user
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  cluster:
    name: homelab-db
  name: lychee
  login: true
  passwordSecret:
    name: lychee-db-credentials
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: lychee
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  name: lychee
  owner: lychee
  cluster:
    name: homelab-db
