---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lychee-db-credentials
  namespace: database
spec:
  encryptedData:
    password: AgCaMXpiu6JXzWH4NL25cxl02fJnH9cED1VKKuElkcBUBOa+v5b0MgEiq/mMV99TnFHcuZ/xwWkPSUZng+/2LsTXsf5Ut3ZJdGGfrwCxup+6+T84RwfHlKRb9690Lgsime9bLQUXNvU3ObjydK0kYz/kOsBKN7DEBVTFYYBgVy64UicE9PR8q1mNrEjKK+lthiHDd8LOMcrcEpKJ3AnerZTsEttRWj3W/dr59ZU9CDXZcnVvofWHO/oVmmPaSDmuuY+itpAvT2TGwXYvtwV1m4rLQlnEg3XoLc3TAmm+NHv1V7DeA2xhfIqdZZY9Ff6iJ/UibC48Lcsog541+XCbjogaE1CLHLZXChjypDK162xRWLdQekg6tRZF5OCvobYSV4vYtDBHZ+v52lcGZ+az+5zFPOPn3u2BqnP2QOLHdtwDKOnLSeEUYc9S0iY6mMKy6vVcBouQwmcqE9qyQdTd3tzo6WpbVPijWw1lL5ZfVdiXLfBO6dkmFcJNGL7zpfAZ5xmWd7r6fakOPsoWFPfmfDYy70Pr3MfBKVf9nQkn3uwL6Q9BriKBnf2ppPhZDbk5Fr6i31m5CZ/nguFpHv4JX6bPW/PdIsvAveiGMM89Sk+57r3AwFVuP8z1XCsObmIPJJbj3M2A9M57N5MobBZt0QkBSzyq60JfHjrSdZMBWIq6Iz/dOLU1CIA2kaUzIIsQVntQF3wWvWYrj9f32quJhw==
    username: AgAoxeCHZfSa4vnOCCfGtUg/vcq6U1sBhAx9pIfEy5dHbuV7Lp/X4yTKxjEeZAhAbUeBiYpuvuoLklAy5hDwIWwynm0k+82sh3UOdlfTJyGCeaHLggvX7QRUID1Dm/oLp5OITiZzEjCiH8vj6SxUpYk56FhAUddctVbaxjd8MGrNwDq+MhIovmNgCxWra8q2iSMpG+WJsOHxbFtQLnh/LmH+eeindqRkzuy+Na6/H7cx/dz9Cnhlf+AVWjJxPvWM7ziAivHugg6I0V0S6qL3PQpy+OoUnw4WYumIrBlI56Wd2cIlxTGVcr4b0zefWELAEmHT8TzAviZymKjPwOoeFf1a4/xtyG5QskWlRP4YXncMwh6Q1forBP1S1g5dNMCP5B+QAriupXEh8a+o2ubWK6u9hhbo7d6biXIJbI2zVI0bzc3l5ruuBAqY5mboDEnckEAf9+j9a1DhQTjYdPXxdDuG4Foa9eN05HczHYO0BHNNazOJ6ApsGCahH79wIcWxJZg2e/eGwLFAO7/5cfQCcpnWppEjvV9WjSkkRWFqN7FGSpaJRr2hSAVxcfI/wKy8r1hpzipexpp82W/3JQLr2zjd2FwcPnhxt1MdLdM2gNIx4kPSDTiAUzX8RS1bk1loPTQuAVFLvEL1GjUm1lZlvdyLXAnK+EF0TfDOOYqfWV0oFNMu/ITOJ39r9/r+1ITiSfEl/ctNtEg=
  template:
    metadata:
      name: lychee-db-credentials
      namespace: database
