---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lychee-db-credentials
  namespace: lychee
spec:
  encryptedData:
    password: AgDMltZ/nAtXuQCgsnA03fjpBXdkWbdwwjHpFoPQwRC5Bshg4PJrx2AHgtSCCppsltQLHu35fbLuNhFDGre3mZQZDxsgDPbn7BPjgK2qWYcQQgsH7+O7FGQve1aoMlkZs/U4xFJV/WzP5HCIpte3n9yipoOQU6EhXQV14YT7em4QDhQMaEgsxjWjfocPGHA9RuWGxbET5CrdsvJ/ovLRF8ND/hwLcrduA2sv2zQZR/U10ujWCpGdNvAQy41owxbn2VTNyrVsElyGm46TZfU8/cTs3UKDxPuykUBtviqfggbK/EqZcCnW5LzTb0yK1KPvuFCt8DJ1+ttAwphkcHc8L7xA6MsWx4cldFYuPGoxXGG6ASVCXYjSFz/hanJR2kkAQjR/dzGZ3NMPvPBk2SgERH7rtSdkj+0y3OD4FeY03AeoNU3aoNOyIhFRjY9Q9tCUB4nbwcUylMLLxkr2z5tcCQu86EZuuIsKB069A/a6I+d7wJ9lq7BgmutYOhxDl33CHdg25AFlIAnlBpMtb+iu1VGW65ziwq1UadXalyEisTw09OvWH4fxD4WMNpw/NTXdLUVpGdbqlOWNXPGsxb0gc1qk4OaLG35WduhfsK0n5QBTcz0oPNHwDuckYFnoR3LKb2fddlP9Ol/m4GyS082zSIHuDoOjRwThBh3itdKBTbMNNx4JIzfDXxelNCLwJWj0XO3XcFn5cAYYjmruMhQSJg==
    username: AgB8zT2iAUVKnAnZfC9VThfMsQvLWqUAeT+xQlNNJELj+y0KrSpc2TfAPl1NEyCEyRMAG7zPxp7Jg45lUb2wMMWY+ov/z6Mx3tSDx4gw+fjqFQQ10Kjg9eu5ZZyNowdGYEU+zp/MJwzJ/r7bGBH9hZ2XEV+lKsyyQIh6AmrjDoUAGcrpszyhcXBziBU2vZJsvuZvoLTyfBkcaR/mhXUEybb7fSHr7tPasbT3bFWrSf8GU5Tse5RDl2jBSZ1shOOGkaSZPBVUZ/PEj9DHQiX6d0zW2r5XF5lDz0SsNtxfjtIAmCxhR78K50ZKb8HzNmGHqbRN8uhFcs/yAqVGbKClLRn8+SGRosZGtv/P1Su5zZmx9nG0hWzfWlE0Lc5U7uHwsncidSjqLmkQstM4BUl8eti9tJ+JpcKNkN6VlIAQDf3iBsxbd7ufxTytybs7erzAi1plqVkTcyj0oHQ4gs0fPr7joTrdU+SlvknF5FiXuLxajAIGG9rpPrJU45OQMu9vqrLEpw03LY5z9iayAedt1yzyCUPrGpM72hajvmvWIFDd+V39yTTfsVXFFI5DlgzQBuEWv841DYoMqCnSy1P6iUxsLllmNxpeXqQEm96FkCa99V978O5i9DPj9BiYjuYF9f23MygHwDha094sH9t+iG8VSRMv08SJUuUWNQp8XUTamZ7jgpUC6/qpYcXmLcVD+uRHfQUFzN4=
  template:
    metadata:
      name: lychee-db-credentials
      namespace: lychee
