apiVersion: apps/v1
kind: Deployment
metadata:
  name: lychee
  namespace: lychee
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lychee
  template:
    metadata:
      labels:
        app: lychee
    spec:
      containers:
        - name: lychee
          image: lycheeorg/lychee:latest
          ports:
            - name: http
              containerPort: 80
          env:
            - name: TIMEZONE
              value: "Europe/Rome"
            - name: APP_URL
              value: "https://photo.fferrando.cc"
            - name: DB_CONNECTION
              value: "pgsql"
            - name: DB_HOST
              value: "homelab-db-rw.database.svc.cluster.local"
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: "lychee"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: lychee-db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lychee-db-credentials
                  key: password
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          volumeMounts:
            - name: config
              mountPath: /conf
            - name: uploads
              mountPath: /uploads
              subPath: Filippo/Foto
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: lychee-config
        - name: uploads
          persistentVolumeClaim:
            claimName: lychee-uploads
