apiVersion: v1
kind: PersistentVolume
metadata:
  name: lychee-uploads-nfs
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: lychee-nfs
  mountOptions:
    - vers=4
    - proto=tcp
  nfs:
    server: 192.168.10.101
    path: /mnt/vault/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lychee-uploads
  namespace: lychee
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: lychee-nfs
  resources:
    requests:
      storage: 1Ti
