---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-token
  namespace: cloudflared
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    token: AgCkraVHWCPQbG9/bCzOXIZmXClp6kfvcXiaD41USK/FXsDg4rv+9q63jAy1bqv6FZE9pV0UA/mjJ+TwruydcplOZzOGvAYJo1K5JcHD20Fr0RQ60+V8095iPwH2KIWjeV7cGgvJvVjm4uZtNbV5l2dTZrPY2OhFeRFeojZVJ2GnIk6fgYb0iX80DlGa1D3B0N5lc9rlFd4XwJQhpDGsLBk/qJuo7hvFQOtYoIlCd1htT69xEHXDRkEwjlvv2nf+idSkFZzMOa0RoOmv+HOQHLVALlHgxW5zYlKC8UyEPNoYhWKGLhIaE5jBNoqlooEPqZ8fgplnLC1TQeAUNFBByEwJxmF9zbuQlpBAYkNgSzkbMrSm9gfXh1mK7mbQzGJ8eqzgo5UEvoaB3M3overReNF8qrL0trEzV5ruU080HhrZr1bBwL59spGOCcXEDKGf3vPDLx17LP/lYgzQIm2e/VfQtrzI5Rvr80t1yudZn/0l0ZcpqZGVPmDnzOatxF/r3tBROqfGcVfItu7Igy9oCQziXrcd8W4K2wtw7z4viTaFZd82bW/QLjmAWdcz/6DCWQNdudcEBcoFyL10lqzTs+kYZSBplYmsIVn/8JMirl1bA5Yf4a5W/l/OuRo4ErEe1UE1l2IxH+OBeOUPCN0z1huIHawFpt6OWbjMGVpXSCmOVuFXhQ+TtMpV9CARTfPSpBCGm0DAYbttU1o1YwmgkDy8zRQe0qMaTZGSRuMCaTL1MFJeg0+/04DGbZ/g21zUWXrl4w6j9kZv8jz3OsbI7dwpx92TpD9p6Maoc1HsC0DC2TQblWppcm8ipJxgHPdHiY+yA5hX4Nn2n3dZqbVOpEQ2FSzATqRV4F8qof4xcRo0L71osixdI8Uz/dWs7tbvEj6eugZa6h4hJWG3TqPA/MS4ivY0PXngyWGc5LjsbRgtDNmmErhLb4T7
  template:
    metadata:
      name: tunnel-token
      namespace: cloudflared
