apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: librephoto-protected-media
  namespace: librephoto
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single-replica
  resources:
    requests:
      storage: 10Gi
