---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: librephoto-db-credentials
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    password: AgCAasRKZIKeC0j4fSwmNGjbAh/5GIqRxvuuJsyOBUgw/6H403pEigQc6zzYPCaA1pOkkGpGhn/+NK1ee3cU4TLfPiKkIm9e2dnfAbCb33t/ibx9USJNThYffZIxQrDERp7T6/x+tHT7z5z9KxOHDvk8pwCSp4c+7tlmTrIqKH/JbYYPWmfMpAjxf/PFQelZ1WGofnGwHlHMWgQ5J0CXsGkfmikTvbvygn/EQc/c/7sVvmD4ZE1o2pGCJ8LXIXfyNwi4qOMKLoB7BieRtpxJxUix1hWs5Tv1WByvCp6WKRJ9rBhr9K/8m0mkA11om1ZuBRdoP+hc2nefaJE1AXP094hNminCdiYfR/NX3RQmP9VCWE7nvWIXX6AIZsijLo6leJDyfkA5MTNDHSxrD7+1N0waeJeJaXMwLkukozR7dpjrCalKgqCo5uD+036EVhKF7iQGGwXKTQRFbKOpwxCPJtk9PTFCXzWT2PnqzRYUcwn/FjgYdnolpbr30Ab3VimFfFXNt5L1YAGPHGBei6JJICr7nH+gwnYxD7kzQTVs5Iwn73kevUrExl2wZP+l1IdMz8GWJvWoSypY6XZnkZQ4KASdfjkzboHzhi1D0TFPdPHULK4R0xoNz9524Zeouks90oaMhmypBrZaasTSmj8fkpOPU/PsEF3A8fL9R0xDN9AhG34HuJPf4hD2XJLmwaMgRWSl0uA1Fdvg7TsvHYdLbw==
    username: AgC6Z7wjkdPKl33N4LO33+c9T70Y5CzZRV2gAzyJClgviembjbBIznO3VbHSpvNluV/EEyKbyh3sW73aawx36W3cgfIdoDYv7rSW7hOhPZm4Aj2Qv6u/LjwRMQBWJxsTnSSiwl8nXGlkh7FsuXwNRcQJI3aD24wGlPqT/bgtXj3hr+ypP4H42FrFS9QVXLu9dZKQ5Rn6zIOGjHe4QcE9IN4nh8GSFZkTSdVasMt9gUU+aIZCyqcw6pzWIzNcteEpSZs3ggr5dMclrNAkUj/AqR7gh6ssOjJEBCDEoQLC7X4WGrIIyMH5YRR0syRefORBdeEpkUax5bDw048QVooJNpVzKE7GJiJbLfZOLq5aGxRco4nNzXxaALeAHdjuudgQcUoiirzdu/s4EM1GXNqYeifBWf+gTvX6ROVFAj/CCjz/TYQEEzWF2WDvNX3NkV0Mvz24TKMKjBREzKwQqL6NPL4EaOF/QbJWbvHVJMTasiPi6a/yDem/xxyg9X3IkLhJREzqhrxl6/JpS9nyFjvXF5ynh4NdfCHfzmKhNRpaDQuJHIR0mAAvvIiKYsOq8SVD1pCC66lTukzflO9q2qXb5IT3NV+Djn6QCahNuCZWWzyxhN/3son6NlwOduqe6dRmv0zUvjNMn3dnmgFp+CkDXVogrka+pVjsjl3Q49oYjRybc7cCis0RP16gccsrOHgil3VaZtXn/gs2dNkH
  template:
    metadata:
      name: librephoto-db-credentials
      namespace: database
