---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: librephoto-db-credentials
  namespace: librephoto
spec:
  encryptedData:
    password: AgCJxujCDBaEmc0s1Bgrw1ext0gHvC94mcGv/MvM26TlTWg1tZPL1cOxiKraks1yIxaSBzhYr5Mrv5/uD71e4O0hG/rFAGlpuihymCVuiZF4bp4FT3e+S4xlXZhP5tDgUAQL50FBiFp1LlsSuKoO2ewnQWFR8AqPwLo0JfS/SnPEmhGNDOnAhkHjs0ERUawi+MMYYiSZAqcvZTrvfQYsf/KWEqpFGOvlxGEOJarB2DQ99Mc4YZJ8IIdggUzV9sYBtiUS9yP410it7E5az0xctfISmITa2G8nJhVSSVDVm/2HUnHTfv2UEMf+kaO7wXpEDfdSq6rmg+VfVY4JoM/TJCd7F3iHbePnQ0VG5zftLGBSHt8bxNjHNi55wdaArdZtTg0zy8YAMEDNffQUirLWJ1Y0NOs5I0iilEAsPdyPXJnrIZJNfewMuy9FE0PCZyBy8nRTqhHBtQLVbxXZTMFNiaORUCMqSPEvQB/1VclkAVFul4h0L6PP4e5gwEzeWVb3nzsDJQ1WoL834wrQw0wWKb3aD7ZucFl1RaXwJQth0cUHwqQ0gqfdn17ECv+cT6faKEYpRF79UPYkf+u4Bh7bGc1UqK3FGsUa5KQC6MPmGKxhfYyEOdWiEun5/2kzoXjEH/Ur0nxh1M5rgCIlEK93aKkf6Q5nW+VWy9977SOoBIxdIaAuJc0XbNArVQB2xu55XdXxBS8izS0r9fZYEfBbvg==
    username: AgA2rj7LuY6TNR2ggrMDjFtbOUFRVl+1DhqLAjpAIzv+aSrKMDGWTxr1y8dPWNwQE/1mlOsWPLgRIAM9sP6aeVMQ37W0sFVVa6NlNBzSXf/xqoxF51+99hAt+4wZPg0g7QraDKzXuNXprPchF0TUjHorJIdU47t0/XxllQqUNN+yEnHmWNvzkffPEMvGbYgKsD1LYbIwyuviZRLmvcjZNWdqZftUAPWsPk/pNa4Prm9HDLJ9Oot9dW1ObPldiwLvPqb4fHafBDZ3VbBq6hqxWrx2ra0KQzEOnVoxsdPKviQkB5CSZQTulIHiTNHEzWqm9VyBLDvcPKKKKlTeXVc/uY8S+Dqpzn7cZn7mpsjioNQ3nby4Em6X8UHP+h5I6jU2jFfyl5Rxp5MNmgdK7eDoR4VA69AB1V0F+/45omNySsKoeVWdhO6eLmdCXQQ2ifI0Yf/L3zZZJSv5n01HjPf0CVKsXlAHw+5f4g2U6jShSFsL6fVVDWMXFZvMWDnTQSCFxrgroFDPgElU3BFC+jUnLTobQgI9oFtqaopa5klfx1HGjXb0AlIR+uCQ9zzhr8srX10Nf/xRzVNwPbmVWK2hLVaV+MSFXx09JznKXsuYLqqovile7DwjpwiIWJo3qgFy57oWyWFwE8nZsPL8VuLVAidPaYTM71VOz4qPyg/lBmmjVX+bcUsXXP7P0QlhnwBslQcVMw5dD9R0qiTL
  template:
    metadata:
      name: librephoto-db-credentials
      namespace: librephoto
