apiVersion: apps/v1
kind: Deployment
metadata:
  name: librephoto-frontend
  namespace: librephoto
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: librephoto-frontend
  template:
    metadata:
      labels:
        app: librephoto-frontend
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - librephoto-backend
              topologyKey: kubernetes.io/hostname
      containers:
        - name: frontend
          image: reallibrephotos/librephotos-frontend:1.1.0
          env:
            - name: BACKEND_HOST
              value: "librephoto-backend"
            - name: BACKEND_PORT
              value: "8001"
          ports:
            - containerPort: 3000
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: librephoto-frontend
  namespace: librephoto
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  selector:
    app: librephoto-frontend
