apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: librephoto-internal
  namespace: librephoto
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`photo.internal.fferrando.cc`)
      kind: Rule
      services:
        - name: librephoto-proxy
          port: 80
  tls:
    secretName: photo-internal-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: librephoto-public
  namespace: librephoto
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  entryPoints:
    - cf-public
  routes:
    - match: Host(`photo.fferrando.cc`)
      kind: Rule
      services:
        - name: librephoto-proxy
          port: 80
