---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: librephoto-secret-key
  namespace: librephoto
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    secret-key: AgB1+u1QyAWgmAhMItj4umgs4+6t4vVarBijY0SFQWJVDCUtQRyESWdL4E72ivcaUON80wS8oChK/dsTxeltg2BXWoYe/6C47DYCX1OzjLmrgaLFPwTXUnavDfYz/538muD6DtK3f5AGRnzgCjUUuJAbb0GadNsJEHcecArgOoanRY0py/Bj6zmO0TOZlH29elBktt2VWklpZKA7NVnPXY1xc2Us/Gc6qzqDtaOUfLiuEBA6oXG/zNramdmBnywSYK5HYVOJHtX0sqUG9C2dGKwoyQ/K6veEKlK1I4ULa+Ezkh/R8km+vLI1iVxxXpZLhZcvyDuS+O0F1ZjkXRrZEI4AO3J0pxsDg7fRo29pLL9C6jMtrSQIhxwfmwsdyIX+LsVJv3R04FC8k9yWPMO12TkVPyU8edw1cMcGpZDSUZgCg7PI3sBzUuS8ATXSzjWgTC+GuL7I7nuE47nK0JJq1tL4TAmIR5Tz6bBkyWSIlpbTzQGxmRVEvdZrtYrJ2+Hgr/abBrOBB+JDXsQ/Xub7pdtriXOOKWk8zO/gtqnVIB8yGroHZ0LEP0sObNcjGxKTa7ptpz8A5jZYSeEb4fk7/kN2J7J0NRbpY/i5T1PH5T8/EfNuk4w4v04DNMmrcnCfmM2y9dsIUD0/9EPj3hQ+w5MdaqWqTUHBkLjzEhdAiP81ui5tx2IQJed96IxIXgjwv5qMw/xYZW8IXxlbtHmXSthYqV363Ug6Gd3+xkLPrZr2aGO4+Hf4Gf3gQjpDDA==
  template:
    metadata:
      name: librephoto-secret-key
      namespace: librephoto
