apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hubble-internal-tls
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  secretName: hubble-internal-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - hubble.internal.fferrando.cc
