apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: hedgedoc-user
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  cluster:
    name: homelab-db
  name: hedgedoc
  login: true
  passwordSecret:
    name: hedgedoc-db-credentials
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: hedgedoc
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  name: hedgedoc
  owner: hedgedoc
  cluster:
    name: homelab-db
