---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hedgedoc-db-credentials
  namespace: database
spec:
  encryptedData:
    password: AgCM694BgHIKhHFxctamvXrVIdrduhzpmQaN2Pqp5dR7vGaz2fMeu06aB36uJV5/feu7zhzykMQDBOuvMg85ztWSTCLdsIsZ5E6yjdc8plKJ6NWvQgx0ek2Rs/o/Ncqo8d8GYSarF3wvg/6HV5iC9gfDip5Cm06v/nmgKX8brBGaOZm2AXiDqLYKiXOrsR4wsT7QiS0NyrZJkH7gGEbW6Nl9ypmBYHBeK5vBFCtgW0HkpxnagL2mlbm9pmRUkpiHLNNkxNi6EkADrr3w0KMy7FfhWbhm7u2TpvrbQMWSauvPsqS1Iv/ybKHjHV/8yPfBbMpLxs3h3pzAfOULg4P8jSGauj2qYpefdD5zNGjjjCRizW0eiLN84Ayh6AdAfkgYwBPLIvP3VsKYtXIQvqbrp0yHFyG32Twx6Zc7ril1K5vmfc6a4T3SJxOmxmsZUgi0I7ye04iJ2MxnrPoHD1pwqfA95kL669LZrNOkrxbvWmuN38AvJDH8TH5RHMurDdInWaUJOr/RxQT5Plf/QpK+0g/NHk4arCcXUCrBwMfev058bEM87WdQIe+M2eWXUtvz1Iw0VOH7N1ey8AZE5NN64B02Wh/sCltIEnyOedtR5mcFJnyIJZ9Htb4sXFIfuKt1KZEqbH3LToYWMd8ORhN+ZhYRtwhpjFv0vzXv66ATW776rAVevYSiVr3NCbA8wXIyQmsoyv5tjCtAJ9gnGoDboA==
    username: AgAOcvmpiUImOe49K7GPfPyljNM/uVIl5x0BcW+JPQZv+iDq3s/bPw3kkdCyDyQ1dUw96p5JnLqokFZHtInGBWQEzYKOckeLOA8NkTisSOINcW1rufuc8XsEFTSTbsBonxxKDYM3lo7mm1jhZ0XGsoNHPzk+E8qNavuWmidhY0hiaX/8GbJJUrWdA6RWEQ4qAWATPSTUac/akx4A5EUgX4rLQ6sNxsm1vfmIsmoj52baFpvtRG458TtlS+m+yUOyvefW6yEf/jfKerESBQhgBmpgxNrH7v6/mTR6P2HCWDg8lI+DFjgt+oQ+lGyTwEei901iE1ZLmAPmahdFvqHZlxMQVJFBCz8VrDaK/MzLXHJR6DpfyF/r08ueEdVsReUpGYnzkdDyL+jBiLQ8r50gYUR9t9lIBDoTAIsOQ5vUU4bMdfe6keaLv1wbckaOR26ELohbzCAbgnOdZjQjwwJmVobwy9EqLycTjNg/IdX9edKiNr00SM/nnt1AGLFs1WwGY6kzyG6w3TXlYwc/LYvP0dvUZ4KdGjVuHGD8t2Q4LopONGTleY/NqpXfp2ywRN47FXdm7VvhvLSunX/+KcCEZtfn4yM1pqbhyS2MK8NQGmBEk1cN1aBw4vJ6auOyrzY6ZJoK4EO4TWAjO8yy/Z2Jnjt+ElM51sZIlpr0wXTq5/FdrQ6ClDKQ2tS1Hzw3Kx2kxU8dzJzDl0T73g==
  template:
    metadata:
      name: hedgedoc-db-credentials
      namespace: database
