---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hedgedoc-db-credentials
  namespace: hedgedoc
spec:
  encryptedData:
    password: AgAxHlksSQ8UwtJOG+tb3Qsqmc+28uMVnWqLto5HfMPOpx6bGZkQgGz9UO2LFc8lEYB/Ibg//VpQKvwOjR5BzOx/HETemLKHCQEx1eYsOWrvJRITghSAFi3CCkBKR6gIJMBNFWWJNNSm0P11olWiXaryJH9y9RTqcJCY8hHXL8KKTWexSnUIPza9IVZrTU89kuHyPQOSWwxj4oM/yEUKeNL5I7QX1C4W/NiC8DSjwQFYjLSBijHo0jkR9fnA3jcvSWJsCTaaj1F2iKuDSCkDxATvBovWuYI5JPJVZBebFvUJwMyi9RgY1/a3djlqnv8OfI+4rCkCHJdgYbWUkUlThayovxSFE3FbxIU3zh+rH+YIoluo7DKaQJtHuIaSGe2Te+WUEkabKUEYjsLCVRJj1Pedq8AOMcn4uutV7IGSFNWfOntvQpCjWmitcTZR1BjsD2mlPCLY3E/rZOUicc4E2z46wr7UbmY6qP7L6s74S8etHHRC0MfhMDF3I6DUi6CfqmUgOfYGtiqIrAVNvb9dpPabQ1+0Gm69/4QmxNBCQcolDT905iqZTcAXj+Nk6VrhcpBpJ8s8AZCuz5Mfwea0cFcuq8BAPu+xjmlSeQ9+CmM577iFXPYaP55VNUDLCOPaxg8eGaYc/LRmbjGgS7Uo2dwT1bRlTvW1YImWD31yuhAbzYxwVjgPaq9oFVm4hMHN4jhumq7rrDzCOdbNtprNeQ==
    username: AgDP1UFNYZRBoUu8ZYe/FMNZ3mOGXYOlGtXX/laEO4oUUCgyxp/LxucwyLh15TqQEHS/dWpXTRi8vzm+eHsqHw6FwzIISIe6e7ls/KXj3CNmZuy3ls7sooUTn06Ivz3u/2RhaPdkU92CpJep+zjIEi2BzKrZORWXd/7zG35j+BK/v0dCrPRYKEfy08zjbCsqPOeZrVmAKWOxBtRfn1ZEVI+qtC0GCdhTdLDUugBmmiXJeOYqwDQkJlAE14F6fjKTQUrne4qNpY/agT8Y6xptT2HHHKCS1Mv6UhMi+OD9j9R49TXX9SP38P0stBu3bGy4y8ZhDtcWOKHMyumuYvMz0BeCL9tsrsh2EFAi1f8UXESaREOeMRmmd9hGf1+G2J2TZNlkAC+GMunMNUBuaEXYkqjl+KTPzAkRJgHgG3uA8+Wij68TQcza7aNStFNojuzErsORr2jrpFX8M+pCiLk86N6Syp1pXUWmhVKmhLh6af1QNXHZpiSjJPqErmgfetwmuQL0d6y7/rsxpFlzYLwcI4iSXQX4tf65jMzZVW+kuNc1cG23Vqs2PWdtzy2adH63eoFb0VeEacsHarcg/wz1whQT8XfG50mDpMm68VWgO4wPUXa8pEFsVag7YkS6AyTpKvkV83dom6/Eji4fcVeH3Br0OChHGB7q3gG435eW6WqZrW0ZOV2BcuAYfSqq/JWbNqtrFtLcbamRig==
  template:
    metadata:
      name: hedgedoc-db-credentials
      namespace: hedgedoc
      labels:
        cnpg.io/reload: "true"
