apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: hedgedoc-headers
  namespace: hedgedoc
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hedgedoc
  namespace: hedgedoc
spec:
  entryPoints:
    - cf-public
  routes:
    - match: Host(`doc.fferrando.cc`)
      kind: Rule
      middlewares:
        - name: hedgedoc-headers
          namespace: hedgedoc
      services:
        - name: hedgedoc
          port: 3000
