apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-internal
  namespace: monitoring
spec:
  secretName: grafana-internal-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - stats.internal.fferrando.cc
