prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn-single-replica
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

prometheus-node-exporter:
  securityContext:
    runAsUser: 0
    runAsGroup: 0
    runAsNonRoot: false

grafana:
  adminPassword: "admin" # You will change this in the Grafana UI on first login
  persistence:
    enabled: true
    storageClassName: longhorn-single-replica
    size: 5Gi

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn-single-replica
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
