prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn-single-replica
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

prometheus-node-exporter:
  securityContext:
    fsGroup: 0
    runAsGroup: 0
    runAsNonRoot: false
    runAsUser: 0

  containerSecurityContext:
    privileged: true

  extraArgs:
    - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($|/)
    - --collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs|tmpfs)$

grafana:
  adminPassword: "admin" # You will change this in the Grafana UI on first login
  persistence:
    enabled: true
    storageClassName: longhorn-single-replica
    size: 5Gi

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn-single-replica
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
