---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-db-credentials
  namespace: forgejo
spec:
  encryptedData:
    password: AgAUj7ik6HAAQJjwQEIIj/thzJVyUwDLoYm9N3DdTjG0r2JkqbX7IyIct3Kjho+Jjz87y88Eo3X/OovmGOedwfX7Fbr4pKwiN6ESVzb+cX2C5Fowp0+HT+6r1/JscGKUibJVhUTEwbliCGT+AMcdDeifTjSHKKFLB7/7jJBEXR6//SMTgtMFzAO1zS3SY8d4iB6Eu7yBG2upfhWg6DUXbbysv/WS3XbzMQ/f4RIzKiH6bepJeuAZZes2Lylc2jzkQToTw2bqYBRSBIkzr5TPmkBHqJRRNvUuTQTP4jvsZWJoxwBxxQ5W74QjD7fwQHAcspxZT52AErbapjVrt1K/7LeMYeoLNZSdG9IJuvjXm7JCTVvMPUSCE+TMuGO49ZZTUufQNaddSXB/u+GyXgICX2WZ361NBtiHGZISW74LUuuOLNqke8a/MnY24zE8JEQUJPd7tJ7J5Kc1Q9f8EysJPQvzZ9YGrcbLfvWj+V3A7dRX+Fzf41o/3EkNbNvJ+nMHAehfDACWSQw74/hZFm3SzHuYb3PyKENjjfpT8Mb8vKoBGvbLI/d+0NDP/imVn8d4FlNWZZWxyTjJckFJT7t4jKQa8vOrl40rmooX6GbjZGpfX+FZv2DEG0Kg++0AqVusT7CneI0k7xLG5+j2rEVAdaNuzIjY6ts8sMGqcDFu50c6y8bR3EpJ6ii8zPZDpMZ59PpuAbtDdCt2qOg4hJj4MA==
    username: AgCSaNejfgHjzBKzrxrXJiPq5xXJTAhzpsoeAP7YwUm6kpsSTqOJ/4EsmC38xnpFeTIf0Zpm8qtw9kn1es/hNQjmLBGwbmpSeERd0kyZH0GZ2Wh7JK62ZQyCUR9dZYlz6EI/eK8FzBoUEOzStBnI4xB5YRXOgYRIFFaYG8WAENGWJNmUp4bp4/n6pGLnbkVlkKbSOm3JY+h4avixEPugWaUL5W8RrY+BbWgtxxrVSsAyumCHmPNW3dYo5JaZKTsDMlbCdhA/AbZ9dIXLBgCIT9EralTmB0dhCru8a7klu5Ch4+piwMBKgSWah7rDK/qvgWiSi4w8tluG8vjr9l+4OUGBnJnbFwycKMvHF2Ix8lmUmh9e0MiK7ddrNlXSEDNvRzuLlGAfyXmNeysCFKBb9X73fWmx6YECMFRQywr+oM7AMWB/VK6H1MjsAT6DrL7KgHc9FynpPyGKZT4bQgJ2gJFJ7I4ojsFon3cZuSc9u3ZjBzMjNMfZrMr+8HZT+4+iq98FWPUBsBiVyv2FnlCyp50yRk2w4nClbCX27Jj/i0td1JVVXOBQIos3uOVvjtbZ9mPDiAIc95bHI7bbRWvMeJV7ErCHo5cnxnEcXE5Ibgl1Eogz36WGoJyFpdDYgFT6VDYgz5W8Jg6dWJE4vu/st3wc2FedaC5nCzGpTr03S1U+dEFXCoVpM+U2V5yzsqV4A6+E+HMjUn85
  template:
    metadata:
      name: forgejo-db-credentials
      namespace: forgejo
      labels:
        cnpg.io/reload: "true"
