---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-db-credentials
  namespace: forgejo
spec:
  encryptedData:
    password: AgC18blRk5PrBmQgKRhT1F/p40xTTtkSZJ3ZM8d3OcAYminzObfVC89k7FmWaoOaX6B2q2w1PaH6P4reJR9nt3Anw59LcYX42O/sd9SrkMqnO1vFLxwqbXFFFPrvFvKkSjn4/Cy5ptRIK8GxyKr884T/QJPKJOorapyqfbHErA4yfAbvH3RvaJGHl6aaVDjFueVBK6aME7MCA3md/1DTWJwa9X0+KUY6lAPNcCZ1V6kMnG948/pWu6vvhMAJxRDnIOlmUSgF+GSbVicrnkWOdAWMwUI3SSaeroPru2t2UR2Mav+1SEeWUOcmYFs8fkFHl/OLpD4fgR/GC8DuVJxFIMFAjC4vi/rDdEZOwOn/yMNNt+1Ww6/gkYcDOEvj3/ssccwtj+LeaUaxUk4OGF4w0EWXPgYkQyX/4giQxAuDS0wIra1MbYOEyi/BUEIVXBHJRFGpJlXd2rnHU/YCrbT3J0jKjQJD+8s1euJJGg2xm90cEmsKVNCg0C8sVQAEK3efSJSctZEUXkqG9pliNNWnVAdKCJQJx4Hf7CyFbMSz3sOA/NOUoqibfui5m+zQ0P8SBSMiBzFebRyQQLakhC+UlNoO2kEQeZXiL84VnxN4NUNqQi3C2DrCk3A1Ti+dIR/1BuCTe2d0f6cq684L6em0Ag6k114bQc886TpLIUPtQz4vpOR2HSBn+E5qT5Stpa6250qFEDETkIzTzul9w9pgbw==
    username: AgCY++74206pFSkK+R/gAr6GNOycE97Z9yxw46iPs96SwXYyWEGeNV1BQovAs5TdmMUYzILkNODt+xrvEwOU9UYuM/Ookk6RqaGk9/pN2k4SLJDIdHMqAXuTbsTxtXBTPy4LRC8PBD2+ckMFpniSmfWt/FntdZZNEAUdLUjOkI9DVftQ4K68NM7tQ5vQ1jG8yBQwNJ5RU2YcMlUdNSsEHx/Dlf8pWwyizFhXklIOZZJxuSUZpYEZNpZA6ZJiVPeg5E7iriu0eLw2S2+lQDXatNaSNzlgbWJjaK7BIaesKquL3CGDDuZDQhYZS8Fx4N8WsV2Jo4CPW5OWYFL9jY9fMG3msobwi4npE2xvHI2KDBPH1ma+lZ+ilzqxMtvsleTqHTajp6hA461oxEanyRdCx/YYZTUjoxZ3i+M9PMemekuA34T+c+lXuTg7nUjJxKon4N0lnPIVjc5/NfSDP38sEfx119MqURRzACmFHwOXFGedzmBI56GVz8MCRPPFceYFaAYi/XeuEAk2paqZ6CKmE5kFRXkGRX7qmY/NQsayi4TwqUeOZGTZymFlrdkNEYG2FpSqYHkHE1kk1xO+21G3VUOlMhNya7HlnbtuhpvzOQqFsMqF7feT7+PXQFG9Oh/dQ0BjXLEt180YtCNlMGo8p5KHvNMsICSURD5SGpfhi8IaxIREUujIRI0vkSRAJzGrfEutCn4E3dKf
  template:
    metadata:
      name: forgejo-db-credentials
      namespace: forgejo
      labels:
        cnpg.io/reload: "true"
