---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: forgejo-resend-credentials
  namespace: forgejo
spec:
  encryptedData:
    smtp-password: AgAJHk5e9cYOkiJoLVq8KVPX8lvYbL9h0/O/qEA7QmjoGIdE6YdTNtTQV5GKGK978i2k3rQogssN/vic1zbYU4I0rky4cgerQvIFidcthmIFF6oKmA1eIdL1rhgbIoBbCgSgufVXUsuloEIC3mI7zultNKMx/na328Wfd8w+I0hxTuYLifmGIjX7ViV2gWzHBSata164m+pfoNPcVeT+AkQkUoEnelCBXBlbSrQr/8nkyvNQOHkpIe4qSlRjnSMxLdBcjRwHd+w8IKfuntsbb+P4e0CvU87lk90VDYzvdUZLyDe04AC1NBuugr0fwhxJlsKGW4j1Ndt0UB+8Ts4VTJHg9q7Iu81tQczZtRT8JPQvr+khBhkVz9Da/5pI3c6OPefeePAKq2mWVMKP1XJdb9/PfJxJ1DznZ74EJNhuJv8YyJ7fG9Y6XonmDxbLcnBm0MmfKwlgmi8iPAPF+9k0lvefUO4jqR8zVzSw1e9Ds/TBNsAOceHgn3OnkQCjl7ioQYFtgpavr8+4l7yhILIZN/+OJoF46KVZcbb1XkCD5L8Q23ye2I5awuTzWfHquBoUGUpEEE6APywLEdQi7xw5sFuMvsFFgUvAmYThxlD0/AzCLtiGYyxYi5u5T/NxoiRFrvmFHl7T1wg0mdwQvyHtkYhXYBZvRfOEP8Ou4CTpLIPBRYjQlv2EWE27AFdPM6rm5kzxRA+SHYu/qqLSxmdRTNRU5a5SRHJnZGnHCD/nhbGmtD9o4cI=
    smtp-user: AgASSPxJUulf3egey0vWo4f+/g2sK38ukUadFzf7fo0/50RZCnu14+PCuCMgNs24AVbqj/A6R69tJLk+mEK+Pbf+LJEH7xKnK0t9f49mYao/36ACqC4QIqxxXxsnO+7zxYcUYjAzyI7EAojXjqP4R7axqP1bgKBN6M1t/rq90mGfQmfvN3YTvI4cjlUNO+wlI2AISZQHt/THtFZB9krgolf0iAcUJkpSKey0977Uuw4CNm1k5pO5ErXdC0Pg6Z+X7Cm4gcpb7GbLxHB/gr8viToRW4TSzp3FIfxWX+GC4cyihf/WzV7U3dJSDk4ePtBN3TkV3vjSVHeq1L5V/JfjI1WYCtEXmLf5KYkE2z0XLaGkjZHrFhp5M54btSWwlrri/QRmWKnGy8ZNC4YNXTiDiyypfOlbujHt/anYHsxdV+WSrs8GO8udF3xlEC66fb/Yl4LP5otI3IsgN9lc+MKTq5dfDPt2yS5IkJwRZ7ZTdSFRnqY/uRSaKkYCqqGMxeppVkPxNun2qO3ajCsdo09Ro4CbhAcm1zO03J35FEvGep+/hCRIZKw+KoaDWW3M9fQU25QthZTnnP1mzBs1UG94+Lqgi/0HAXhALBIaAxlMK0sNR3BNWJkGl2ATIFsefo4mFHBFmj3ddTW12D7KmUQbXR+bfakvDeECdFwB6kHZx72TJBWN5YThWkyjdzaNEVqvRKKkcJs/IQo=
  template:
    metadata:
      name: forgejo-resend-credentials
      namespace: forgejo
