[k3s_servers]
magi.fferrando.homelab    ansible_host=192.168.10.100 ansible_user=magi k3s_taint="node-role.kubernetes.io/control-plane=true:NoSchedule"
balthazar.fferrando.homelab ansible_host=192.168.10.102 ansible_user=balthazar
caelium.fferrando.homelab   ansible_host=192.168.10.103 ansible_user=caelium

[k3s_agents]
casper.fferrando.homelab      ansible_host=192.168.10.101 ansible_user=casper

[k3s_cluster:children]
k3s_servers
k3s_agents

[nfs_storage]
casper.fferrando.homelab

[compute]
balthazar.fferrando.homelab
caelium.fferrando.homelab

